include ../../../../doc/webdir.mk
T = nearequal
WEB = $(WEBDIR)/ops/utils/$T
class:
	scp -r classes/uw cspk:/usr/local/bin
doc:
	scp -r javadoc/*.html javadoc/*.css javadoc/resources javadoc/uw $(WEB)



