#!/bin/bash

if [[ $UID != 0 ]];
then
	echo "You must be root to run this script"
	exit 1
fi

CANDIDATE_DIR=/usr/local/spk/ops/candidate
RELEASE_NOTES_DIR=/usr/local/spk/ops/release_notes
WEBDIR=/usr/local/tomcat/instance/test/webapps/soft

cd $CANDIDATE_DIR
VERSION=`cat version`
RELEASE_NOTES="release_notes_$VERSION"
cat notes-* > $RELEASE_NOTES

scp $RELEASE_NOTES webserver:$WEBDIR/release_notes/$RELEASE_NOTES
rm $RELEASE_NOTES

chmod 0666 $RELEASE_NOTES_DIR
mv notes-*[0-9] $RELEASE_NOTES_DIR
#rm notes-*


