#!/bin/bash

if [ $UID -ne 0 ];
then
	echo "You must be root to run this script."
	exit 1
fi

CGI=/var/www/cgi-bin

mkdir -p $CGI/YRC
mkdir -p $CGI/YRC/admin
mkdir -p $CGI/YRC/projects
mkdir -p $CGI/YRC/projects/report

cp cgi-bin/YRC/admin/*.cgi           $CGI/YRC/admin
cp cgi-bin/YRC/projects/*.cgi        $CGI/YRC/projects
cp cgi-bin/YRC/projects/report/*.cgi $CGI/YRC/projects/report

exit 0
