package YRC::PROJECT::REPORT::DEFS;

## MAKE THESE VARIABLES AVAILABLE
require Exporter;
our @ISA = ("Exporter");
our @EXPORT = qw($STARTDATE $ENDDATE $HOST_NAME @LABS %MEMBERS);

## $STARTDATE DECLARATION
## THIS IS THE EARLIEST DATE FROM WHICH WE WILL INCLUDE PROJECTS
$STARTDATE = '2001-01-01';

## $ENDDATE DECLARATION
## THIS IS THE LATEST DATE FROM WHICH WE WILL INCLUDE PROJECTS
$ENDDATE = '2010-12-31';

## THE NAME OF OUR LOCAL HOST IN THE REPORT
## THIS WILL NOT BE PRINTED IN THE NONHOST PORTION OF THE
## REPORT, IF THE RESEARCHER IS FROM THIS HOST
$HOST_NAME = 'University of Washington';

## @LABS DECLARATION
## THIS IS USED TO DETERMINE THE ORDER WHICH PROJECTS ARE   
## PRESENTED IN THE REPORT, AS WELL AS THOSE AFFILIATED WITH
## THE PROJECT FROM THE LOCAL RESOURCE CENTER
## THE GROUPS ARE LISTED THE ORDER WHICH THEY APPEAR IN THIS ARRAY
## ONLY PROJECTS AFFILIATED WITH THESE GROUPS IN THE DB WILL APPEAR IN THE REPORT   
@LABS = ('IntMetab', 'LipidMetab', 'PKPD', 'EnvTox', 'CBNet', 'PMImageD', 'SysMod', 'StatMod', 'SoftDev');

## %MEMBERS DECLARATION
## THIS IS A LIST OF RESEARCHERS ASSOCIATED WITH THE RESOURCE CENTER GROUP LABS
## THE RESEARCHERS ARE LISTED IN ARRAY FOR EACH GROUP, WHICH REPRESENTS THE ORDER
## WHICH THEY WILL APPEAR ON THE REPORT
## THE 6 RESEARCHER FIELDS ARE: NAME, DEGREE, DEPARTMENT, ORGANIZATION, CITY, STATE
## THIS SHOULD REALLY BE MOVED TO XML OR A DATABASE
%MEMBERS = (
   IntMetab=>[
   ],
   LipidMetab=>[
   ],
   PKPD=>[
   ],
   EnvTox=>[
   ],
   CBNet=>[
   ],
   PMImageD=>[
   ],
   SysMod=>[
   ],
   StatMod=>[
   ],
   SoftDev=>[
   ]
);

1;

