#!/bin/bash

if [ $UID -ne 0 ];
then
	echo "You must be root to run this script."
	exit 1
fi

HTML=/var/www/html

mkdir -p $HTML/v2
mkdir -p $HTML/v2/css
mkdir -p $HTML/v2/images
mkdir -p $HTML/v2/tmpl

cp v2/css/*.css	$HTML/v2/css
cp v2/images/*.gif v2/images/*.png $HTML/v2/images
cp v2/tmpl/*.html $HTML/v2/tmpl

exit 0



