/*
 * ThetaShow.java
 *
 * Created on December 16, 2003, 12:49 PM
 */

package uw.rfpk.mda.nonmem.display;

import javax.swing.table.*;
import javax.swing.JTable;
import java.text.DecimalFormat;
import java.awt.*;
import javax.swing.JViewport;
import javax.swing.SwingConstants;

/**
 *
 * @author  jiaji Du
 */
public class MatrixShow extends javax.swing.JFrame {
    
    /** Creates new form MatrixShow */
    public MatrixShow(String[][] data, String[] header, String title, String text) {
        initComponents();
        setTitle(title);
        int dimension = data.length;
        int width, height;
        if(dimension < 4)
        {
            width = 400;
            height = 200;
        }
        else
        {
            width = 600;
            height = 300;
        }
        setSize(width, height);
        jTextPane1.setText(text);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(width - 40, height - 100));
        
        // Format the data
        DecimalFormat f = new DecimalFormat("0.00E00");
        for(int i = 0; i < dimension; i++)
            for(int j = 1; j < data[i].length; j++)
            {
                data[i][j] = String.valueOf(f.format(Double.parseDouble(data[i][j])));
                if(!data[i][j].startsWith("-"))
                    data[i][j] = " " + data[i][j]; 
            }

        // Set table model
        DefaultTableModel tableModel = new DefaultTableModel(data, header);
        jTable1.setModel(tableModel);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        show();    
        
        // Create a column model for the main table.  
        TableColumnModel cm = new DefaultTableColumnModel() {
            boolean first = true;
            public void addColumn(TableColumn tc) {
                // Drop the first column that will be the row header.
                if(first) {first = false; return; }
                tc.setMinWidth(80);
                super.addColumn(tc);
            }
        };
        // Create a column model that will serve the row header table.
        TableColumnModel rowHeaderModel = new DefaultTableColumnModel() {
            boolean first = true; 
            public void addColumn(TableColumn tc) {
                if(first) {
                    tc.setMaxWidth(80);
                    super.addColumn(tc);
                    first = false;
                }
                // Drop the rest of the col;umns.
            }
        };
        
        jTable1.setColumnModel(cm);
        
        // Set up the header column and get it hooked up to everything.
        JTable headerColumn = new JTable(tableModel, rowHeaderModel); 
        jTable1.createDefaultColumnsFromModel();
        headerColumn.createDefaultColumnsFromModel();
        jTable1.setSelectionModel(headerColumn.getSelectionModel());
        jTable1.setRowSelectionAllowed(false);
        rowHeaderModel.getColumn(0).setCellRenderer(new HeaderCellRenderer());
        
        // Make the header column look pretty.
        headerColumn.setRowHeight(20);
        headerColumn.setMaximumSize(new Dimension(80, dimension));
        headerColumn.setBackground(new Color(204, 204, 204));
        headerColumn.setColumnSelectionAllowed(false);
        headerColumn.setCellSelectionEnabled(false);

        // Put it in a viewport.
        JViewport jv = new JViewport();
        jv.setView(headerColumn);
        jv.setPreferredSize(headerColumn.getMaximumSize());

        // Shut off autoResizeMode.
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        // Attach the row headers.
        jScrollPane1.setRowHeader(jv);        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextPane1 = new javax.swing.JTextPane();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(jTextPane1);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Dialog", 0, 14));
        jTable1.setFont(new java.awt.Font("Monospaced", 0, 14));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jTextPane1.setEditable(false);
        jTextPane1.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        getContentPane().add(jTextPane1, gridBagConstraints);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
//        System.exit(0);
    }//GEN-LAST:event_exitForm

    class HeaderCellRenderer extends DefaultTableCellRenderer 
    {
        public Component getTableCellRendererComponent(JTable table,
            Object value,boolean isSelected, boolean hasFocus, int row,int col) 
        {
            super.getTableCellRendererComponent(table,value,isSelected,hasFocus,row,col);
            setHorizontalAlignment(SwingConstants.CENTER);
            return this;
	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
