/*
 * ThetaShow.java
 *
 * Created on December 16, 2003, 12:49 PM
 */

package uw.rfpk.mda.nonmem.display;

import uw.rfpk.mda.nonmem.Utility;
import javax.swing.table.*;
import java.text.DecimalFormat;

/** This class's instance display a vector show on the screen
 *
 * @author  jiaji Du
 */
public class VectorShow extends javax.swing.JFrame {
    
    /** Creates new form VectorShow
     * @param vector a String[] object containing the vector of data values
     * @param header a String[] object containing the headers
     * @param title a String object containing the title of the window
     * @param text a String[] object containing the text to display in the window
     * @param width the width of the window
     */
    public VectorShow(String[] vector, String[] header, String title, String text,
                      int width) 
    {
        initComponents();
        setTitle(title);
        setSize(width, 150);
        jTextPane1.setText(text);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(width - 40, 50));
         
        // Format the data
        int dimension = vector.length;
        DecimalFormat f = new DecimalFormat("0.00E00");
        for(int i = 0; i < dimension; i++)
            vector[i] = Utility.formatData(6, f.format(Double.parseDouble(vector[i])));         
        String[][] data = new String[1][dimension];
        data[0] = vector;
        
        // Set table model
        jTable1.setModel(new javax.swing.table.DefaultTableModel(data, header));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextPane1 = new javax.swing.JTextPane();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(jTextPane1);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Dialog", 0, 14));
        jTable1.setFont(new java.awt.Font("Dialog", 0, 14));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jTextPane1.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        getContentPane().add(jTextPane1, gridBagConstraints);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
//        System.exit(0);
    }//GEN-LAST:event_exitForm
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
    
}
