#!/bin/sh

if [ $UID -ne 0 ];
then
    echo "You must be root to run this program"
    exit 1
fi

source ../../../../../doc/webdir.sh

SERVICE_ROOT=spkrun
SERVICE_HOST=cspkserver

scp ${SERVICE_ROOT}d     ${SERVICE_HOST}:/etc/rc.d/init.d
scp ${SERVICE_ROOT}testd ${SERVICE_HOST}:/etc/rc.d/init.d
scp ${SERVICE_ROOT}d.pl  ${SERVICE_HOST}:/usr/local/bin/spktest
echo "installed ${SERVICE_HOST}:/etc/rc.d/init.d/${SERVICE_ROOT}d "
echo "installed ${SERVICE_HOST}:/etc/rc.d/init.d/${SERVICE_ROOT}testd "
echo "installed ${SERVICE_HOST}:/usr/local/bin/spktest/${SERVICE_ROOT}d.pl"
echo "Note: installation of ${SERVICE_ROOT}d.pl must be completed by the deployment process."

D=${SERVICE_ROOT}d
pod2html $D.pl > $D.pl.html

scp $D.pl.html $WEBHOST:/$WEBDIR/man/$D.pl.html
