#!/bin/sh
#
# chkconfig: 2345 91 9
# description: Starts and stops the SPK run daemon
#

DATABASE=spktest
HOST=localhost
DBUSER=tester
DBPASSWD=tester

SERVICE_NAME=spkrund
LOCKFILE_PATH=/tmp/lock_$SERVICE_NAME

ulimit -c 1000000  # this enables a core dump if the runner crashes

#restart()
start() {
    /usr/local/bin/${SERVICE_NAME}.pl $DATABASE $HOST $DBUSER $DBPASSWD
    echo "started"
}
stop() {
    if [ -f $LOCKFILE_PATH ]; then
       PID=`cat $LOCKFILE_PATH`
       kill $PID
       while sleep 1 && [ -f $LOCKFILE_PATH ]; do
	   if [ -z $SENT ]; then
	       echo "waiting for child processes to terminate"
	       SENT=sent
	   fi
       done
       echo "stopped"
    else
	echo "$SERVICE_NAME is not running"
    fi
}

case $1 in
    restart)
	stop
	start
	;;
    start)
	start
	;;
    stop)
	stop
	;;
esac
