#!/bin/sh
#
# chkconfig 2345 62 38
# description: Starts and stops the job queue server
#

DATABASE=spkdb
DBHOST=dbserver
DBUSER=daemon
DBPASSWD=daemon
BIN=/usr/local/bin/spkprod
MODE=prod

SERVICE_NAME=jobqd
LOCKFILE_PATH=/tmp/lock_$SERVICE_NAME

ulimit -c 10000000  # this enables a core dump if the server crashes

start() {
    $BIN/${SERVICE_NAME}.pl $DBHOST $DATABASE $DBUSER $DBPASSWD $MODE
    echo "started"
}
stop() {
    if [ -f $LOCKFILE_PATH ]; then
       PID=`cat $LOCKFILE_PATH`
       kill $PID
       sleep 1 
       rm -f $LOCKFILE_PATH
       echo "stopped"
    else
	echo "$SERVICE_NAME is not running"
    fi
}

case $1 in
    restart)
	stop
	start
	;;
    start)
	start
	;;
    stop)
	stop
	;;
esac
