Example: Example.o
	g++ Example.c -lgsl -lcblas -latlas -o Example

Example.o: Example.c
	g++ -g -c Example.c

sf_bessel: sf_bessel.o
	g++ sf_bessel.c -lgsl -lcblas -latlas -o sf_bessel

sf_bessel.o: sf_bessel.c
	g++ -g -c sf_bessel.c 

