/*
 * Report.java
 *
 * Created on February 24, 2004, 12:16 PM
 */
package uw.rfpk.testtool;

import java.io.*;
import java.sql.*;
import javax.swing.*;
import rfpk.spk.spkdb.*;
import javax.swing.JOptionPane;
import uw.rfpk.mda.nonmem.*;

/**
 *
 * @author  jiaji
 */
public class UserJob extends javax.swing.JFrame {
    
    /** Creates new form Report */
    public UserJob() {
        initComponents();
        setSize(700, 500);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();

        setTitle("Test Tool");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Open File");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setPreferredSize(new java.awt.Dimension(80, 19));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1);

        jLabel2.setText("  Job ID");
        jPanel2.add(jLabel2);

        jTextField1.setPreferredSize(new java.awt.Dimension(80, 19));
        jPanel2.add(jTextField1);

        jLabel3.setText("  End Code");
        jPanel2.add(jLabel3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cerr", "srun" }));
        jComboBox1.setSelectedIndex(1);
        jComboBox1.setPreferredSize(new java.awt.Dimension(60, 19));
        jPanel2.add(jComboBox1);

        jButton2.setText("Add Report");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setPreferredSize(new java.awt.Dimension(80, 19));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton2);

        jLabel1.setText("  No. of Jobs");
        jPanel2.add(jLabel1);

        jTextField2.setPreferredSize(new java.awt.Dimension(60, 19));
        jPanel2.add(jTextField2);

        jButton3.setText("Add Job");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setPreferredSize(new java.awt.Dimension(80, 19));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jLabel4.setText("Database Host");
        jPanel1.add(jLabel4);

        jTextField3.setText("rose.rfpk.washington.edu");
        jPanel1.add(jTextField3);

        jLabel5.setText("Name");
        jPanel1.add(jLabel5);

        jTextField4.setText("spktest");
        jTextField4.setPreferredSize(new java.awt.Dimension(80, 19));
        jPanel1.add(jTextField4);

        jLabel6.setText("Username");
        jPanel1.add(jLabel6);

        jTextField5.setText("tester");
        jTextField5.setPreferredSize(new java.awt.Dimension(80, 19));
        jPanel1.add(jTextField5);

        jLabel7.setText("Password");
        jPanel1.add(jLabel7);

        jTextField6.setText("tester");
        jTextField6.setPreferredSize(new java.awt.Dimension(80, 19));
        jPanel1.add(jTextField6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String spkInput = jTextArea1.getText();
        if(spkInput.indexOf("<spksource>") == -1 || spkInput.indexOf("<spkdata") == -1 || 
           spkInput.indexOf("<spkmodel>") == -1)
        {
            JOptionPane.showMessageDialog(null, "The text is not a SPK input file", 
                                          "Job Submission Error", 
                                          JOptionPane.ERROR_MESSAGE);          
            return;
        }
        String s = jTextField1.getText();
        String n = jTextField2.getText();
        int m = 0;
        long l = 0L;
        if(!Utility.isPosIntNumber(s))
        {
            JOptionPane.showMessageDialog(null, "The Job ID must be a positive integer", 
                                          "Job Submission Error", 
                                          JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!Utility.isPosIntNumber(n))
        {
            JOptionPane.showMessageDialog(null, "The No. of Jobs must be a positive integer", 
                                          "Job Submission Error", 
                                          JOptionPane.ERROR_MESSAGE);
            return;
        }        
        m = Integer.parseInt(n);
        l = Long.parseLong(s); 
        ArchiveInfo modelArchive = new ArchiveInfo();
        ArchiveInfo dataArchive = new ArchiveInfo();
        for(int i = 0; i < m; i++) 
        {
            String jobAbstract = "Job description " + (i + l);
        
            // Collect model archive information 
            modelArchive.name = "Model " + (i + l);
            modelArchive.description = "Test model " + (i + l); 
            modelArchive.version = "1";
            modelArchive.isNewArchive = true; 
            modelArchive.isNewVersion = false;
            modelArchive.log = "";
  
            // Collect data archive information 
            dataArchive.name = "Dataset " + (i + l);
            dataArchive.description = "Test dataset " + (i + l); 
            dataArchive.version = "1";
            dataArchive.isNewArchive = true; 
            dataArchive.isNewVersion = false;
            dataArchive.log = "";

            // Get the XML documents as String objects
            int index1 = spkInput.indexOf("<spkdata");
            int index2 = spkInput.indexOf("<spkmodel");        
            String source = spkInput.substring(0, index1 - 22);
            String dataset = spkInput.substring(index1 - 22, index2 - 22);
            String model = XMLReader.getModelArchive(spkInput.substring(index2 - 22));
        
            // Get SPK username
            String username = JOptionPane.showInputDialog(null, "Enter SPK username");
            
            // Submit the job
            Database database = new Database(jTextField4.getText(),  
                                             jTextField3.getText(), 
                                             jTextField5.getText(), 
                                             jTextField6.getText(),
                                             username);
            database.submitJob(source, dataset, model, jobAbstract, modelArchive, dataArchive); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String s = jTextField1.getText();
        if(s == "")
            return;
        try
        {
            // Connect to the database
            Connection con = Spkdb.connect(jTextField4.getText(),  
                                           jTextField3.getText(), 
                                           jTextField5.getText(), 
                                           jTextField6.getText());             

            Spkdb.endJob(con, 
                         Long.parseLong(s),
                         (String)jComboBox1.getSelectedItem(),  
                         jTextArea1.getText()); 
            
            // Disconnect to the database
            Spkdb.disconnect(con);  
            
            JOptionPane.showMessageDialog(null, "The job report was put in the database.",
                                          "Database Information", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SpkdbException e) 
        {
            JOptionPane.showMessageDialog(null, e, "SpkdbException", JOptionPane.ERROR_MESSAGE);        
        }
        catch(SQLException e) 
        {
            JOptionPane.showMessageDialog(null, e, "SQLException", JOptionPane.ERROR_MESSAGE);        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser files = new JFileChooser();
        int result = files.showOpenDialog(null);
        if(result != files.APPROVE_OPTION) 
	    return;
        File file = files.getSelectedFile();
        StringBuffer buffer = new StringBuffer();        
        try
        {
            BufferedReader reader = new BufferedReader(new FileReader(file));
            boolean done = false;
            while(!done)
            {
                // Read a line
                String line = reader.readLine();                            
                if(line == null) 
                    done = true;
                else
                    buffer.append(line).append("\n");
            }	    
            reader.close(); 
            
            // Display the file text
            jTextArea1.setText(buffer.toString());
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(null, e, "IOException", JOptionPane.ERROR_MESSAGE);        
        }         
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new UserJob().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
    
}
