/**********************************************************************
From:   Resource Facility for Population Kinetics                    
        Department of Bioengineering Box 352255                      
        University of Washington                                     
        Seattle, WA 98195-2255                                       

This file is part of the System for Population Kinetics (SPK), which
was developed with support from NIH grants RR-12609 and P41-
EB001975. Please cite these grants in any publication for which this
software is used and send a notification to the address given above.

SPK is Copyright (C) 1998-2003, by the University of Washington,
Resource Facility for Population Kinetics, and is made available as
free open source software under the terms of the University of
Washington Free-Fork License as a public service.  A copy of the
License can be found in the COPYING file in the root directory of this
distribution.
**********************************************************************/
package uw.rfpk.mda.saamii.compartment;

import java.awt.Font;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.geom.Point2D;
import java.awt.Cursor;
import java.awt.BasicStroke;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author  jiaji Du
 */
public class Diagram extends javax.swing.JPanel {
    
    /** Creates new form Diagram */
    public Diagram(DesignTool frame) {
        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.EtchedBorder());
        initComponents();
        area = new Dimension(0, 0);
        this.frame = frame;
        model = new Model(frame.models); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        renameMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        attributeMenuItem = new javax.swing.JMenuItem();
        compDialog = new javax.swing.JDialog();
        compNameLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        compOKButton = new javax.swing.JButton();
        compCancelButton = new javax.swing.JButton();
        compHelpButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        compUnitsTextField = new javax.swing.JTextField();
        forceButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        compEqTextArea = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        delayDialog = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        fluxDialog = new javax.swing.JDialog();
        fluxNameLabel = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fluxEqTextArea = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        fluxVariableTextField = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        fluxOKButton = new javax.swing.JButton();
        fluxCancelButton = new javax.swing.JButton();
        fluxHelpButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField12 = new javax.swing.JTextField();
        inputDialog = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        sampleDialog = new javax.swing.JDialog();
        sampleNameLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sampleUnitsTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        sampleDataTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        sampleEqTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        sampleOKButton = new javax.swing.JButton();
        sampleCancelButton = new javax.swing.JButton();
        sampleHelpButton = new javax.swing.JButton();
        forceDialog = new javax.swing.JDialog();
        compLabel = new javax.swing.JLabel();
        turnOffRadioButton = new javax.swing.JRadioButton();
        associateDataRadioButton = new javax.swing.JRadioButton();
        forceEquationRadioButton = new javax.swing.JRadioButton();
        dataNameTextField = new javax.swing.JTextField();
        forceTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ffOKButton = new javax.swing.JButton();
        ffCancelButton = new javax.swing.JButton();
        ffHelpButton = new javax.swing.JButton();
        splitInputDialog = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();

        renameMenuItem.setText("Rename");
        renameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameMenuItemActionPerformed(evt);
            }
        });

        jPopupMenu1.add(renameMenuItem);

        deleteMenuItem.setText("Delete");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });

        jPopupMenu1.add(deleteMenuItem);

        attributeMenuItem.setText("Attributes");
        attributeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attributeMenuItemActionPerformed(evt);
            }
        });

        jPopupMenu1.add(attributeMenuItem);

        compDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        compDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        compDialog.setTitle("Compatment Attributes");
        compDialog.setModal(true);
        compDialog.setResizable(false);
        compNameLabel.setText("Name:  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 8, 12);
        compDialog.getContentPane().add(compNameLabel, gridBagConstraints);

        compOKButton.setText("OK");
        compOKButton.setPreferredSize(new java.awt.Dimension(75, 25));
        compOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compOKButtonActionPerformed(evt);
            }
        });

        jPanel1.add(compOKButton);

        compCancelButton.setText("Cancel");
        jPanel1.add(compCancelButton);

        compHelpButton.setText("Help");
        compHelpButton.setPreferredSize(new java.awt.Dimension(75, 25));
        jPanel1.add(compHelpButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        compDialog.getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setText("Units:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        compDialog.getContentPane().add(jLabel1, gridBagConstraints);

        compUnitsTextField.setPreferredSize(new java.awt.Dimension(100, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        compDialog.getContentPane().add(compUnitsTextField, gridBagConstraints);

        forceButton.setText("Forcing Function");
        forceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forceButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        compDialog.getContentPane().add(forceButton, gridBagConstraints);

        jLabel2.setText("Equations:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 12, 0, 0);
        compDialog.getContentPane().add(jLabel2, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(3, 80));
        jScrollPane1.setViewportView(compEqTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        compDialog.getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel36.setText("Enter variables to model (separated by space):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 12);
        compDialog.getContentPane().add(jLabel36, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        compDialog.getContentPane().add(jTextField13, gridBagConstraints);

        delayDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel8.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 10, 12);
        delayDialog.getContentPane().add(jLabel8, gridBagConstraints);

        jLabel10.setText("Delay Time:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 5, 6);
        delayDialog.getContentPane().add(jLabel10, gridBagConstraints);

        jTextField1.setPreferredSize(new java.awt.Dimension(100, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 12);
        delayDialog.getContentPane().add(jTextField1, gridBagConstraints);

        jLabel28.setText("Number of Compartments:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 12, 2, 6);
        delayDialog.getContentPane().add(jLabel28, gridBagConstraints);

        jLabel29.setText("Transfer Coefficient:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 5, 6);
        delayDialog.getContentPane().add(jLabel29, gridBagConstraints);

        jLabel30.setText("Delay Width:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 6);
        delayDialog.getContentPane().add(jLabel30, gridBagConstraints);

        jLabel31.setText("Equations defining Fractional Distribution:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 0, 12);
        delayDialog.getContentPane().add(jLabel31, gridBagConstraints);

        jButton2.setText("OK");
        jButton2.setPreferredSize(new java.awt.Dimension(75, 25));
        jPanel9.add(jButton2);

        jButton3.setText("Cancel");
        jPanel9.add(jButton3);

        jButton4.setText("Help");
        jButton4.setPreferredSize(new java.awt.Dimension(75, 25));
        jPanel9.add(jButton4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 12, 12);
        delayDialog.getContentPane().add(jPanel9, gridBagConstraints);

        jScrollPane4.setViewportView(jTextArea4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 80;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        delayDialog.getContentPane().add(jScrollPane4, gridBagConstraints);

        jComboBox1.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        delayDialog.getContentPane().add(jComboBox1, gridBagConstraints);

        fluxDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        fluxDialog.setTitle("Transfer Attributes");
        fluxNameLabel.setText("Transfer Coefficient Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 2, 12);
        fluxDialog.getContentPane().add(fluxNameLabel, gridBagConstraints);

        jLabel32.setText("Flow Rate:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 12, 1, 12);
        fluxDialog.getContentPane().add(jLabel32, gridBagConstraints);

        jLabel33.setText("Flow Rate Units:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 5, 3);
        fluxDialog.getContentPane().add(jLabel33, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        fluxDialog.getContentPane().add(jTextField10, gridBagConstraints);

        jLabel34.setText("Enter variables to model (separated by space):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 12, 0, 12);
        fluxDialog.getContentPane().add(jLabel34, gridBagConstraints);

        jScrollPane3.setViewportView(fluxEqTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 4, 12);
        fluxDialog.getContentPane().add(jScrollPane3, gridBagConstraints);

        jLabel35.setText("Equations:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        fluxDialog.getContentPane().add(jLabel35, gridBagConstraints);

        fluxVariableTextField.setPreferredSize(new java.awt.Dimension(100, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 4, 12);
        fluxDialog.getContentPane().add(fluxVariableTextField, gridBagConstraints);

        fluxOKButton.setText("OK");
        fluxOKButton.setPreferredSize(new java.awt.Dimension(75, 25));
        fluxOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fluxOKButtonActionPerformed(evt);
            }
        });

        jPanel11.add(fluxOKButton);

        fluxCancelButton.setText("Cancel");
        fluxCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fluxCancelButtonActionPerformed(evt);
            }
        });

        jPanel11.add(fluxCancelButton);

        fluxHelpButton.setText("Help");
        fluxHelpButton.setPreferredSize(new java.awt.Dimension(75, 25));
        jPanel11.add(fluxHelpButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 12, 12, 12);
        fluxDialog.getContentPane().add(jPanel11, gridBagConstraints);

        jCheckBox1.setText("Flow rate is fixed at value of:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        fluxDialog.getContentPane().add(jCheckBox1, gridBagConstraints);

        jTextField12.setPreferredSize(new java.awt.Dimension(100, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 12);
        fluxDialog.getContentPane().add(jTextField12, gridBagConstraints);

        inputDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        inputDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        inputDialog.setTitle("Input Attributes");
        inputDialog.setModal(true);
        inputDialog.setResizable(false);
        jLabel16.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        inputDialog.getContentPane().add(jLabel16, gridBagConstraints);

        jLabel20.setText("Units:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        inputDialog.getContentPane().add(jLabel20, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 12, 12);
        inputDialog.getContentPane().add(jTextField2, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        jPanel4.setBorder(new javax.swing.border.TitledBorder(null, "Input Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10)));
        jRadioButton1.setText("Bolus");
        buttonGroup2.add(jRadioButton1);
        jPanel4.add(jRadioButton1);

        jRadioButton2.setText("Infusion");
        buttonGroup2.add(jRadioButton2);
        jPanel4.add(jRadioButton2);

        jRadioButton3.setText("Primed Infusion");
        buttonGroup2.add(jRadioButton3);
        jPanel4.add(jRadioButton3);

        jRadioButton4.setText("Equation");
        buttonGroup2.add(jRadioButton4);
        jPanel4.add(jRadioButton4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        inputDialog.getContentPane().add(jPanel4, gridBagConstraints);

        jPanel6.setLayout(new java.awt.GridLayout(6, 2));

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel21.setText("Amount:");
        jPanel6.add(jLabel21);

        jPanel6.add(jTextField3);

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel22.setText("Constant Rate:");
        jPanel6.add(jLabel22);

        jPanel6.add(jTextField4);

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel23.setText("Event Start:");
        jPanel6.add(jLabel23);

        jPanel6.add(jTextField5);

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel24.setText("Event Stop:");
        jPanel6.add(jLabel24);

        jPanel6.add(jTextField6);

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel25.setText("Repeat Every:");
        jPanel6.add(jLabel25);

        jPanel6.add(jTextField7);

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel26.setText("No. of Repeats:");
        jPanel6.add(jLabel26);

        jPanel6.add(jTextField8);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        inputDialog.getContentPane().add(jPanel6, gridBagConstraints);

        jPanel7.setLayout(new java.awt.GridLayout(4, 1));

        jButton1.setText("Save");
        jPanel7.add(jButton1);

        jButton5.setText("Edit");
        jPanel7.add(jButton5);

        jButton6.setText("Add");
        jPanel7.add(jButton6);

        jButton7.setText("Delete");
        jPanel7.add(jButton7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 12);
        inputDialog.getContentPane().add(jPanel7, gridBagConstraints);

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel27.setText("Equation:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 12, 2, 0);
        inputDialog.getContentPane().add(jLabel27, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        inputDialog.getContentPane().add(jTextField9, gridBagConstraints);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        inputDialog.getContentPane().add(jSeparator1, gridBagConstraints);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(453, 103));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setPreferredScrollableViewportSize(new java.awt.Dimension(450, 100));
        jTable1.setPreferredSize(new java.awt.Dimension(300, 100));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 12);
        inputDialog.getContentPane().add(jScrollPane2, gridBagConstraints);

        jButton8.setText("Split Input");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        inputDialog.getContentPane().add(jButton8, gridBagConstraints);

        jButton9.setText("OK");
        jButton9.setPreferredSize(new java.awt.Dimension(75, 25));
        jPanel8.add(jButton9);

        jButton10.setText("Cancel");
        jPanel8.add(jButton10);

        jButton11.setText("Help");
        jButton11.setPreferredSize(new java.awt.Dimension(75, 25));
        jPanel8.add(jButton11);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        inputDialog.getContentPane().add(jPanel8, gridBagConstraints);

        sampleDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        sampleDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        sampleDialog.setTitle("Sample Attributes");
        sampleDialog.setModal(true);
        sampleDialog.setResizable(false);
        sampleNameLabel.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 6, 12);
        sampleDialog.getContentPane().add(sampleNameLabel, gridBagConstraints);

        jLabel17.setText("Units:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 12, 2, 4);
        sampleDialog.getContentPane().add(jLabel17, gridBagConstraints);

        sampleUnitsTextField.setPreferredSize(new java.awt.Dimension(100, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        sampleDialog.getContentPane().add(sampleUnitsTextField, gridBagConstraints);

        jLabel18.setText("Associate with Data Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 12, 2, 4);
        sampleDialog.getContentPane().add(jLabel18, gridBagConstraints);

        sampleDataTextField.setPreferredSize(new java.awt.Dimension(100, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 12);
        sampleDialog.getContentPane().add(sampleDataTextField, gridBagConstraints);

        jLabel19.setText("Equations:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 12, 2, 0);
        sampleDialog.getContentPane().add(jLabel19, gridBagConstraints);

        sampleEqTextArea.setPreferredSize(new java.awt.Dimension(260, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 12, 0, 12);
        sampleDialog.getContentPane().add(sampleEqTextArea, gridBagConstraints);

        sampleOKButton.setText("OK");
        sampleOKButton.setPreferredSize(new java.awt.Dimension(75, 25));
        jPanel3.add(sampleOKButton);

        sampleCancelButton.setText("Cancel");
        jPanel3.add(sampleCancelButton);

        sampleHelpButton.setText("Help");
        sampleHelpButton.setPreferredSize(new java.awt.Dimension(75, 25));
        jPanel3.add(sampleHelpButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        sampleDialog.getContentPane().add(jPanel3, gridBagConstraints);

        forceDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        forceDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        forceDialog.setTitle("Forcing Function");
        forceDialog.setLocationRelativeTo(this);
        forceDialog.setModal(true);
        forceDialog.setResizable(false);
        compLabel.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 7, 0);
        forceDialog.getContentPane().add(compLabel, gridBagConstraints);

        turnOffRadioButton.setSelected(true);
        turnOffRadioButton.setText("Turned Off");
        buttonGroup1.add(turnOffRadioButton);
        turnOffRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOffRadioButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        forceDialog.getContentPane().add(turnOffRadioButton, gridBagConstraints);

        associateDataRadioButton.setText("Associate with Data Name:");
        buttonGroup1.add(associateDataRadioButton);
        associateDataRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associateDataRadioButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        forceDialog.getContentPane().add(associateDataRadioButton, gridBagConstraints);

        forceEquationRadioButton.setText("Equation for the Forcing Function:");
        buttonGroup1.add(forceEquationRadioButton);
        forceEquationRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forceEquationRadioButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        forceDialog.getContentPane().add(forceEquationRadioButton, gridBagConstraints);

        dataNameTextField.setPreferredSize(new java.awt.Dimension(100, 19));
        dataNameTextField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 12);
        forceDialog.getContentPane().add(dataNameTextField, gridBagConstraints);

        forceTextField.setPreferredSize(new java.awt.Dimension(300, 19));
        forceTextField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 12, 0, 12);
        forceDialog.getContentPane().add(forceTextField, gridBagConstraints);

        ffOKButton.setText("OK");
        ffOKButton.setPreferredSize(new java.awt.Dimension(75, 25));
        ffOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffOKButtonActionPerformed(evt);
            }
        });

        jPanel2.add(ffOKButton);

        ffCancelButton.setText("Cancel");
        ffCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffCancelButtonActionPerformed(evt);
            }
        });

        jPanel2.add(ffCancelButton);

        ffHelpButton.setText("Help");
        ffHelpButton.setPreferredSize(new java.awt.Dimension(75, 25));
        jPanel2.add(ffHelpButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        forceDialog.getContentPane().add(jPanel2, gridBagConstraints);

        splitInputDialog.setTitle("Split Input");
        splitInputDialog.setLocationRelativeTo(this);
        jScrollPane5.setViewportView(jTextArea5);

        splitInputDialog.getContentPane().add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jButton12.setText("OK");
        jButton12.setPreferredSize(new java.awt.Dimension(75, 25));
        jPanel10.add(jButton12);

        jButton13.setText("Cancel");
        jPanel10.add(jButton13);

        jButton14.setText("Help");
        jButton14.setPreferredSize(new java.awt.Dimension(75, 25));
        jPanel10.add(jButton14);

        splitInputDialog.getContentPane().add(jPanel10, java.awt.BorderLayout.SOUTH);

        setLayout(new java.awt.BorderLayout());

        setToolTipText("");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

    }//GEN-END:initComponents

    private void fluxOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fluxOKButtonActionPerformed
        Element.Flux flux = (Element.Flux)model.selectedElement;
        String[] newList = fluxVariableTextField.getText().trim().split(" ");
        
        // Find removed variables and remove them from Model.variables
        Vector changedList = removedItem(flux.variables, newList);
        for(int i = 0; i < changedList.size(); i++)
            Model.variables.remove((String)changedList.get(i));
        
        // Find added variables
        changedList = removedItem(newList, flux.variables);
        for(int i = 0; i < changedList.size(); i++)
        {
            if(Model.variables.getProperty((String)changedList.get(i)) == null)
                Model.variables.setProperty((String)changedList.get(i), "?");
            else
            {
                JOptionPane.showMessageDialog(null, "The variable '" +  (String)changedList.get(i) + 
                                              "' has already been defined in another place.",
                                              "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        // Update flux attributes
        flux.variables = newList;
        flux.equations = fluxEqTextArea.getText().trim();
        String[] eqs = flux.equations.split("\n");
        for(int i = 0; i < eqs.length; i++)
        {
            for(int j = 0; j < newList.length; j++)
            {
                if(eqs[i].split("=")[0].trim().equals(newList[j]))
                    Model.variables.remove(newList[j]);
                if(eqs[i].split("=")[0].trim().equals(flux.name))
                    Model.variables.remove(flux.name);
            }
        }
        frame.variableDialog.setVariableList();
        if(frame.isModelApplied)
            frame.jButton1.doClick();
        fluxDialog.setVisible(false);
    }//GEN-LAST:event_fluxOKButtonActionPerformed

    private void fluxCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fluxCancelButtonActionPerformed
        fluxDialog.setVisible(false);
    }//GEN-LAST:event_fluxCancelButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        splitInputDialog.setSize(320, 300);
        splitInputDialog.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void ffCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffCancelButtonActionPerformed
        forceDialog.setVisible(false);
    }//GEN-LAST:event_ffCancelButtonActionPerformed

    private void ffOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffOKButtonActionPerformed
        isForcingFunctionOK = true;
        forceDialog.setVisible(false);
    }//GEN-LAST:event_ffOKButtonActionPerformed

    private void compCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compCancelButtonActionPerformed
        compDialog.setVisible(false);
    }//GEN-LAST:event_compCancelButtonActionPerformed

    private void forceEquationRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forceEquationRadioButtonActionPerformed
        forceTextField.setEnabled(true);
        dataNameTextField.setEnabled(false);
    }//GEN-LAST:event_forceEquationRadioButtonActionPerformed

    private void associateDataRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associateDataRadioButtonActionPerformed
        forceTextField.setEnabled(false);
        dataNameTextField.setEnabled(true);
    }//GEN-LAST:event_associateDataRadioButtonActionPerformed

    private void turnOffRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOffRadioButtonActionPerformed
        forceTextField.setEnabled(false);
        dataNameTextField.setEnabled(false);
    }//GEN-LAST:event_turnOffRadioButtonActionPerformed

    private void forceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forceButtonActionPerformed
        compLabel.setText("Compartment Name:  " + model.selectedElement.name);
        forceTextField.setText(model.selectedElement.name + ".FF=");
        isForcingFunctionOK = false;
        forceTextField.setCaretPosition(model.selectedElement.name.length() + 4);
        forceDialog.setSize(340, 210);
        forceDialog.setVisible(true);
    }//GEN-LAST:event_forceButtonActionPerformed

    private void compOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compOKButtonActionPerformed
        Element.Compartment comp = (Element.Compartment)model.selectedElement;
        if(isForcingFunctionOK)
        {

            if(turnOffRadioButton.isSelected())
                comp.force = "Turned off";
            if(associateDataRadioButton.isSelected())
                comp.force = "Data: " + dataNameTextField.getText();
            if(forceEquationRadioButton.isSelected())
                comp.force = "FF: " + forceTextField.getText();
        }
        comp.equations = compEqTextArea.getText();
        if(frame.isModelApplied)
            frame.jButton1.doClick();
        compDialog.setVisible(false);
    }//GEN-LAST:event_compOKButtonActionPerformed

    private void attributeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attributeMenuItemActionPerformed
        if(model.selectedElement instanceof Element.Compartment)
        {
            compNameLabel.setText("Compartment Name:  " + model.selectedElement.name);
            compEqTextArea.setText("");
            compDialog.setSize(332, 300);
            compDialog.setLocation(x + 200, y + 100);
            compDialog.setVisible(true);
        }
        if(model.selectedElement instanceof Element.Delay)
        {
            for(int i = 2; i <= 50; i++)
                jComboBox1.addItem(String.valueOf(i));
            delayDialog.setSize(311, 324);
            delayDialog.setLocation(x + 200, y + 100);
            delayDialog.setVisible(true);
        }
        if(model.selectedElement instanceof Element.Flux && 
           ((Element.Flux)model.selectedElement).element1 != null)
        {
            fluxNameLabel.setText("Transfer Coefficient Name:  " + model.selectedElement.name);
            fluxDialog.setSize(360, 320);
            fluxDialog.setLocation(x + 200, y + 100);
            fluxDialog.setVisible(true);
        }
        if(model.selectedElement instanceof Element.Input)
        {
            inputDialog.setSize(500, 400);
            inputDialog.setLocation(x + 200, y + 100);
            inputDialog.setVisible(true);
        }
        if(model.selectedElement instanceof Element.Sample)
        {
            Element.Sample s = (Element.Sample)model.selectedElement;
            String text = s.name + " =";
            for(int i = 0; i < s.compartments.size(); i++)
            {
                if(i != 0) text += " + ";
                else text += " ";
                text += " " + ((Element)s.compartments.get(i)).name;
            }
            sampleNameLabel.setText("Sample Name:  " + s.name);
            sampleEqTextArea.setText(text);
            sampleDialog.setSize(312, 290);
            sampleDialog.setLocation(x + 200, y + 100);
            sampleDialog.setVisible(true);
        }
    }//GEN-LAST:event_attributeMenuItemActionPerformed

    private void renameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameMenuItemActionPerformed
        String name = JOptionPane.showInputDialog(null, "Enter new name.", model.selectedElement.name);
        if(name != null && !name.trim().equals(""))
        {
            model.selectedElement.name = name;
            if(frame.isModelApplied)
                frame.jButton1.doClick();
            repaint();
        }
    }//GEN-LAST:event_renameMenuItemActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        model.remove(model.selectedElement);
        if(frame.isModelApplied)
            frame.jButton1.doClick();
        repaint();
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if(tempElement != null && (evt.getModifiers() & evt.BUTTON1_MASK) != 0 && start != null)
        {            
            last = evt.getPoint();
            last.setLocation(last.getX() / frame.scale, last.getY() / frame.scale);           
            tempElement.xCenter += (last.getX() - start.getX());
            tempElement.yCenter += (last.getY() - start.getY());
            start = last;
            repaint();
        }        
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if(!frame.pickedElement.equals("")) return;
        start = evt.getPoint();
        start.setLocation(start.getX() / frame.scale, start.getY() / frame.scale);        
        x = (int)start.getX();
        y = (int)start.getY();

        if(evt.isPopupTrigger())
            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
        if((evt.getModifiers() & evt.BUTTON1_MASK) != 0)
            gc2D.setXORMode(Color.white);
      
        for(int i = 0; i < Model.elements.size(); i++)
        {
            if(((Element)Model.elements.get(i)).contains(x, y))
            {
                model.selectedElement = (Element)Model.elements.get(i);
                if(!evt.isPopupTrigger())
                    tempElement = (Element)model.selectedElement.clone();
                else
                    tempElement = null;
                return;
            }
        }
        for(int i = 0; i < Model.fluxes.size(); i++)
        {
            if(((Element)Model.fluxes.get(i)).contains(x, y))
            {
                model.selectedElement = (Element)Model.fluxes.get(i);
                return;
            }
        }
        for(int i = 0; i < model.inputs.size(); i++)
        {
            if(((Element)model.inputs.get(i)).contains(x, y))
            {
                model.selectedElement = (Element)model.inputs.get(i);
                if(!evt.isPopupTrigger())
                    tempElement = (Element)model.selectedElement.clone();
                else
                    tempElement = null;
                return;
            }
        }
        for(int i = 0; i < model.samples.size(); i++)
        {
            if(((Element)model.samples.get(i)).contains(x, y))
            {
                model.selectedElement = (Element)model.samples.get(i);
                if(!evt.isPopupTrigger())
                    tempElement = (Element)model.selectedElement.clone();
                else
                    tempElement = null;
                return;
            }
        }
        model.selectedElement = null;
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if(tempElement != null && (evt.getModifiers() & evt.BUTTON1_MASK) != 0 && start != null && last != null)
        {
            last = null;
            gc2D.setPaintMode();
            isMouseDragged = false;
            model.selectedElement.xCenter = tempElement.xCenter;
            model.selectedElement.yCenter = tempElement.yCenter;
            tempElement = null;
            repaint();
        }
        if (evt.isPopupTrigger()) 
            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
        final int W = 50;
        final int H = 50;
        boolean changed = false;
        if (SwingUtilities.isRightMouseButton(evt)) 
        {

        } 
        else 
        {
            int x = evt.getX() - W/2;
            int y = evt.getY() - H/2;
            if (x < 0) x = 0;
            if (y < 0) y = 0;
            Rectangle rect = new Rectangle(x, y, W, H);
            scrollRectToVisible(rect);

            int this_width = (x + W + 2);
            if (this_width > area.width) {
                area.width = this_width; changed=true;
            }

            int this_height = (y + H + 2);
            if (this_height > area.height) {
                area.height = this_height; changed=true;
            }
        }
        if (changed) {
            //Update client's preferred size because
            //the area taken up by the graphics has
            //gotten larger or smaller (if cleared).
            setPreferredSize(area);

            //Let the scroll pane know to update itself
            //and its scrollbars.
            revalidate();
        }
        repaint();
    }//GEN-LAST:event_formMouseReleased

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        x = (int)(evt.getX() / frame.scale);
        y = (int)(evt.getY() / frame.scale);
        if(frame.pickedElement.equals("compartment"))
        {
            Element.Compartment compartment = new Element.Compartment(x, y, model);
            Model.elements.add(compartment);                
            frame.clearButton.setEnabled(true);
            frame.addButton.setEnabled(true);
            frame.pickedElement = "";
            repaint();
        }
        else if(frame.pickedElement.equals("delay"))
        {
            if(model.nElement == 9)
            {
                JOptionPane.showMessageDialog(null, "The total number of Compartments and Delays must be <= 9.",
                                              "Input Error", JOptionPane.ERROR_MESSAGE);
                frame.pickedElement = "";
                setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                return;
            }
            Element.Delay delay = new Element.Delay(x, y, model);
            model.elements.add(delay);                
            frame.clearButton.setEnabled(true);
            frame.addButton.setEnabled(true);            
            frame.pickedElement = "";
            repaint();
        }
        else if(frame.pickedElement.equals("flux"))
        {
            
            
/*            
            if(startElement == null)
            {
                startElement = getSelectedElement();
                if(startElement == null)
                {
                    frame.pickedElement = "";
                    setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                }
                return;   
            }
*/
            
            if(startElement == null && !isBackgroundClicked)
            {
                startElement = getSelectedElement();
                if(startElement == null)
                    isBackgroundClicked = true;
                return;   
            }
            else if(startElement == null && isBackgroundClicked)
            {
                endElement = getSelectedElement();
                isBackgroundClicked = false;
                frame.pickedElement = "";
                setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                if(endElement != null)
                    addFlux();
                return;   
            }
            else
            {
                endElement = getSelectedElement();
                if(startElement instanceof Element.Delay)
                {
                    if(endElement instanceof Element.Delay && startElement != endElement)
                    {
                        JOptionPane.showMessageDialog(null, "A flux from a Delay to another Delay is not allowed.",
                                                      "Input Error", JOptionPane.ERROR_MESSAGE);
                        startElement = null;
                        frame.pickedElement = "";
                        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                        return;
                    }
                    if(endElement == null)
                    {
                        addFlux();
                        startElement = null;
                        frame.pickedElement = "";
                        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                        return;
                    }
                }
                if(startElement instanceof Element.Compartment && startElement == endElement)
                {
                    startElement = null;
                    endElement = null;
                    frame.pickedElement = "";
                    setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    return;                    
                }
            }
            if(startElement != null && endElement != startElement)
                addFlux();
            frame.pickedElement = "";
        }
        else if(frame.pickedElement.equals("input"))
        {
            Element element = getSelectedElement();
            if(element instanceof Element.Compartment)
            {
                inputElement.add(element);
                return;
            }
            else
            {
                if(inputElement.size() == 1)
                {
                    for(int i = 0; i < model.inputs.size(); i++)
                    {
                        Vector compartments = ((Element.Input)model.inputs.get(i)).compartments;
                        if(compartments.size() == 1 && compartments.get(0) == inputElement.get(0))
                        {
                            frame.pickedElement = "";
                            inputElement = new Vector();
                            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                            return;
                        }
                    }
                }
                if(inputElement.size() > 0)
                {
                    Element.Input input = new Element.Input(inputElement, x, y, model);
                    inputElement = new Vector();
                    model.inputs.add(input);                    
                    repaint();
                }
            }
            frame.pickedElement = "";
        }
        else if(frame.pickedElement.equals("sample"))
        {
            Element element = getSelectedElement();
            if(element instanceof Element.Compartment)
            {
                inputElement.add(element);
                return;
            }
            else
            {
                if(inputElement.size() > 0)
                {
                    Element.Sample sample = new Element.Sample(inputElement, x, y, model);
                    inputElement = new Vector();
                    model.samples.add(sample);                
                    repaint();
                }                              
            }
            frame.pickedElement = "";
        }
        if(frame.isModelApplied)
            frame.jButton1.doClick();
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_formMouseClicked
    
    private Element getSelectedElement()
    {
        for(int i = 0; i < model.elements.size(); i++)
        {
            Element element = (Element)model.elements.get(i);
            if(element.contains(x, y))
                return element;
        }
        return null;
    }
    
    private void addFlux()
    {
        boolean isExist = false;
        for(int i = 0; i < model.fluxes.size(); i++)
        {
            Element.Flux flux = (Element.Flux)model.fluxes.get(i);
            if(flux.element1 == startElement && flux.element2 == endElement)
            {
                isExist = true;
                break;
            }
        }
        if(!isExist)
        {
            Element.Flux flux = new Element.Flux(startElement, endElement, model);
            model.fluxes.add(flux);               
            startElement = null;
            endElement = null;
            repaint();
        }    
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton associateDataRadioButton;
    private javax.swing.JMenuItem attributeMenuItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton compCancelButton;
    private javax.swing.JDialog compDialog;
    private javax.swing.JTextArea compEqTextArea;
    private javax.swing.JButton compHelpButton;
    private javax.swing.JLabel compLabel;
    private javax.swing.JLabel compNameLabel;
    private javax.swing.JButton compOKButton;
    private javax.swing.JTextField compUnitsTextField;
    private javax.swing.JTextField dataNameTextField;
    private javax.swing.JDialog delayDialog;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JButton ffCancelButton;
    private javax.swing.JButton ffHelpButton;
    private javax.swing.JButton ffOKButton;
    private javax.swing.JButton fluxCancelButton;
    private javax.swing.JDialog fluxDialog;
    private javax.swing.JTextArea fluxEqTextArea;
    private javax.swing.JButton fluxHelpButton;
    private javax.swing.JLabel fluxNameLabel;
    private javax.swing.JButton fluxOKButton;
    private javax.swing.JTextField fluxVariableTextField;
    private javax.swing.JButton forceButton;
    private javax.swing.JDialog forceDialog;
    private javax.swing.JRadioButton forceEquationRadioButton;
    private javax.swing.JTextField forceTextField;
    private javax.swing.JDialog inputDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JMenuItem renameMenuItem;
    private javax.swing.JButton sampleCancelButton;
    private javax.swing.JTextField sampleDataTextField;
    private javax.swing.JDialog sampleDialog;
    private javax.swing.JTextArea sampleEqTextArea;
    private javax.swing.JButton sampleHelpButton;
    private javax.swing.JLabel sampleNameLabel;
    private javax.swing.JButton sampleOKButton;
    private javax.swing.JTextField sampleUnitsTextField;
    private javax.swing.JDialog splitInputDialog;
    private javax.swing.JRadioButton turnOffRadioButton;
    // End of variables declaration//GEN-END:variables
    public void paintComponent(Graphics gc) 
    {
        super.paintComponent(gc);
        gc2D = ((Graphics2D)gc);
        gc2D.setBackground(Color.white);
        gc2D.setFont(new Font("SansSerif", Font.BOLD, 10));
        gc2D.setStroke(new BasicStroke(2.0f));
        gc2D.setPaintMode();
        gc2D.scale(frame.scale, frame.scale);
        model.draw(gc2D);
        if(tempElement != null) tempElement.drawBoundary(gc2D);
    }

    private Vector removedItem(String[] oldList, String[] newList)
    {
        Vector removed = new Vector();
        String text = "";
        for(int i = 0; i < newList.length; i++)
            text += " " + newList[i];
        for(int i = 0; i < oldList.length; i++)
            if(text.indexOf(oldList[i]) == -1)
                removed.add(oldList[i]);
        return removed;
    }
   
    
    private DesignTool frame;
    private Graphics2D gc2D;
    private Point2D start, last;
    private int x,y;
    protected Model model;
    protected Element startElement = null;
    protected Element endElement = null;
    private Dimension area;
    private boolean isMouseDragged = false;
    private boolean isBackgroundClicked = false;
    private boolean isForcingFunctionOK = false;
    protected Element tempElement;
    private Vector inputElement = new Vector();
}
