#include "NonmemKeyword.h"

const std::string NonmemKeyword::THETA         = "THETA";
const std::string NonmemKeyword::ETA           = "ETA";
const std::string NonmemKeyword::EPS           = "EPS";
const std::string NonmemKeyword::OMEGA         = "OMEGA";
const std::string NonmemKeyword::SIGMA         = "SIGMA";
const std::string NonmemKeyword::PRED          = "PRED";
const std::string NonmemKeyword::RES           = "RES";
const std::string NonmemKeyword::WRES          = "WRES";
const std::string NonmemKeyword::ETARES        = "ETARES";
const std::string NonmemKeyword::WETARES       = "WETARES";
const std::string NonmemKeyword::IPRED         = "IPRED";
const std::string NonmemKeyword::IRES          = "IRES";
const std::string NonmemKeyword::IWRES         = "IWRES";
const std::string NonmemKeyword::IETARES       = "IETARES";
const std::string NonmemKeyword::IWETARES      = "IWETARES";
const std::string NonmemKeyword::PPRED         = "PPRED";
const std::string NonmemKeyword::PRES          = "PRES";
const std::string NonmemKeyword::PWRES         = "PWRES";
const std::string NonmemKeyword::PETARES       = "PETARES";
const std::string NonmemKeyword::PWETARES      = "PWETARES";
const std::string NonmemKeyword::CPRED         = "CPRED";
const std::string NonmemKeyword::CRES          = "CRES";
const std::string NonmemKeyword::CWRES         = "CWRES";
const std::string NonmemKeyword::CETARES       = "CETARES";
const std::string NonmemKeyword::CWETARES      = "CWETARES";
const std::string NonmemKeyword::DV            = "DV";
const std::string NonmemKeyword::ORGDV         = "ORGDV";
const std::string NonmemKeyword::MDV           = "MDV";
const std::string NonmemKeyword::ID            = "ID";
const std::string NonmemKeyword::F             = "F";
const std::string NonmemKeyword::Y             = "Y";
const std::string NonmemKeyword::T             = "T";
const std::string NonmemKeyword::P             = "P";
const std::string NonmemKeyword::A             = "A";
const std::string NonmemKeyword::EVID          = "EVID";
const std::string NonmemKeyword::DADT          = "DADT";
const std::string NonmemKeyword::AMT           = "AMT";
const std::string NonmemKeyword::CMT           = "CMT";
const std::string NonmemKeyword::PCMT          = "PCMT";
const std::string NonmemKeyword::R             = "R";
const std::string NonmemKeyword::D             = "D";
const std::string NonmemKeyword::ALAG          = "ALAG";
const std::string NonmemKeyword::FO            = "FO"; // ef-oh
const std::string NonmemKeyword::F0            = "F0"; // ef-zero
const std::string NonmemKeyword::S0            = "S0"; // es-zero
const std::string NonmemKeyword::RATE          = "RATE";
const std::string NonmemKeyword::TIME          = "TIME";
const std::string NonmemKeyword::TSCALE        = "TSCALE";
const std::string NonmemKeyword::S             = "S";
const std::string NonmemKeyword::DROP          = "DROP";
const std::string NonmemKeyword::SKIP          = "SKIP";
