#! /bin/bash
list_method="plain grid miser"
list_job[1]="273"
list_job[2]="275"
list_job[3]="274"
list_neval[1]="1000"
list_neval[2]="10"
list_neval[3]="1000"
index=0
mv MontePars.h MontePars.original
for method in $list_method
do
	let index++
	job=${list_job[$index]}
	neval=${list_neval[$index]}
	#
	sed < MontePars.original > MontePars.h  \
		-e "s/method *= *[a-z]*/method = $method/" \
		-e "s/\[ *nEval *\] *= *{ *[0-9]* *}/[ nEval ] = { $neval }/"
	make monteDriver
	echo "./monteDriver"
	echo "cat result.xml | sed  -n '/^ *[0-9.e+-]* *\$/p'  > monteDriver.$job"
	./monteDriver
	cat result.xml | sed  -n '/^ *[0-9.e+-]* *$/p'  > monteDriver.$job 
	sed -n '/^ *[0-9.e+-]* *$/p'  < result-$job.xml > result.$job
	if ./NearEqual monteDriver.$job result.$job 1e-3 1e-3
	then
		list_msg[$index]="Ok"
	else
		list_msg[$index]="Error"
	fi
done
mv MontePars.original MontePars.h
index=0
for method in $list_method
do
	let index++
	msg=${list_msg[$index]}
	echo "Test of $method: $msg"
done
