#!/bin/bash

# Startup script for Tomcat
#
# chkconfig: 345 84 16
# description: Tomcat jakarta JSP server
#
#
#Necessary environment variables
export JAVA_HOME="/usr/java/j2sdk1.4.2_03"
export CATALINA_HOME="/usr/local/tomcat/jakarta-tomcat-5.0.18"
TOMCAT_START=$CATALINA_HOME/bin/startup.sh
TOMCAT_STOP=$CATALINA_HOME/bin/shutdown.sh

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

#Check for tomcat script
if [ ! -f $CATALINA_HOME/bin/catalina.sh ]
then
    echo "Tomcat not available..."
    exit
fi

start() {
    echo -n "Starting Tomcat: "
    su tomcat -c $TOMCAT_START
    echo
    touch /var/lock/subsys/tomcatd
}

stop() {
    echo -n $"Shutting down Tomcat: "
#    su tomcat -c $TOMCAT_STOP
    $TOMCAT_STOP
    rm -f /var/lock/subsys/tomcatd
    echo
}

status() {
    ps ax --width=1000 | grep "[o]rg.apache.catalina.startup.Bootstrap start" | awk '{printf $1 " "}' | wc | awk '{print $2}' > /tmp/tomcat_process_count.txt
   read line < /tmp/tomcat_process_count.txt
if [ $line -gt 0 ]; then
    echo -n "tomcatd ( pid "
    ps ax --width=1000 | grep "[o]rg.apache.catalina.startup.Bootstrap start" | awk '{printf $1 " "}'
    echo -n ") is running..."
    echo
else
    echo "Tomcat is stopped"
fi
}

case "$1" in
    start)
	start
	;;
     stop)
	stop
	;;
     restart)
	stop
	sleep 3
	start
	;;
     status)
	status
	;;
     *)
	echo "Usage: tomcatd {start|stop|restart|status}"
     exit 1
esac

