#!/bin/sh

echo "This installer has been modified from the CVS/original version."
echo "This installs stuff on localhost only."

source ../../../../../doc/webdir.sh

SERVICE_ROOT=spkcmp
SERVICE_HOST=localhost

cp ${SERVICE_ROOT}d /etc/rc.d/init.d
cp ${SERVICE_ROOT}testd /etc/rc.d/init.d
cp ${SERVICE_ROOT}d.pl /usr/local/bin/spktest
cp ${SERVICE_ROOT}monitord /etc/rc.d/init.d

echo "installed ${SERVICE_HOST}:/etc/rc.d/init.d/${SERVICE_ROOT}d"
echo "installed ${SERVICE_HOST}:/etc/rc.d/init.d/${SERVICE_ROOT}testd"
echo "installed ${SERVICE_HOST}:/usr/local/bin/spktest/${SERVICE_ROOT}d.pl"
echo "installed ${SERVICE_HOST}:/etc/rc.d/init.d/${SERVICE_ROOT}monitord"

D=${SERVICE_ROOT}d

#scp $D.pl.html $WEBHOST:/$WEBDIR/man/$D.pl.html

