#!/bin/sh

#
# This deamon keeps checking if the SPK Compiler daemon is running
# in the production environement.  If not, it re-starts it.
#
# By Sachiko Honda
# July 07, 2005
#
LOCK_FILE=/tmp/lock_spkcmpd

while [ 1 ]
do
   VAL=`ps -elf | awk '/\/usr\/local\/bin\/spkprod\/spkcmpd.pl spkdb/ {print $4}' | wc -l`

   if [ $VAL = 0 ]
      then
         echo "The spkcmp deamon desn't seem running..."
         if [ -f $LOCK_FILE ]
            then
               echo "Deleting $LOCK_FILE..."
               rm $LOCK_FILE
         fi
         echo "Starting the daemon..."
         /etc/rc.d/init.d/spkcmpd start
         echo "spkcmpd re-started." | mail -s "SPK Compiler Daemon was found dead in the production environment." honda99@u.washington.edu
   fi
   sleep 300 
done
