#!/bin/sh
#
# chkconfig: 2345 91 9
# description: Starts and stops the SPK compiler deaemon
#

DATABASE=spktest
HOST=localhost
DBUSER=tester
DBPASSWD=tester

SERVICE_NAME=spkcmpd

LOCKFILE_PATH=/tmp/lock_$SERVICE_NAME

#restart()
start() {
    /usr/local/bin/compilerd.pl $DATABASE $HOST $DBUSER $DBPASSWD
}
stop() {
    PID=`cat $LOCKFILE_PATH`
    kill $PID
}

case $1 in
    restart)
	;;
    start)
	start
	;;
    stop)
	stop
	;;
esac
