#!/bin/bash

yum install perl perl-CPAN perl-YAML -y

echo "Updating /etc/hosts"
sed -i "s/^\(127.0.0.1\)\(.*\)$/\1\2 aspkserver cspkserver cspk aspk dbserver jobqserver webserver/" /etc/hosts


echo "Running Configuration for SPK"
./setup.pl

echo "Restarting MySQL"
/etc/init.d/mysql restart

echo "Creating database layout"
mysql create spkdb

echo "Loading data"
mysql spkdb <db/api/schema.sql
mysql spkdb <db/api/basedata.sql
mysql spkdb <db/api/permissions.sql



