#!/bin/sh
#
# chkconfig: 2345 91 9
# description: Starts and stops the production SPK runtime daemon
#              Optional second argument, pvm, specifies using PVM 

DATABASE=spkdb
DBHOST=dbserver
DBUSER=daemon
DBPASSWD=daemon
BIN=/usr/local/spk/bin
MODE=prod
SHOST=jobqserver
SPORT=9000
MAXPROCS=4
if [ -z $2 ]; then
   PVM=off
else
   if [ $2 = pvm ]; then
      PVM=on
   fi
fi
SERVICE_NAME=spkrund
LOCKFILE_PATH=/tmp/lock_$SERVICE_NAME

ulimit -c 10000000  # this enables a core dump if the compiler crashes

start() {
    $BIN/${SERVICE_NAME}.pl $DATABASE $DBHOST $DBUSER $DBPASSWD $MODE $SHOST $SPORT $PVM $MAXPROCS
    echo "started"
}
stop() {
    if [ -f $LOCKFILE_PATH ]; then
       PID=`cat $LOCKFILE_PATH`
       kill $PID
       if [ $? -ne 0 ]; then
           rm -f $LOCKFILE_PATH
           echo "stopped"
       else
	   while sleep 1 && [ -f $LOCKFILE_PATH ]; do
	       if [ -z $SENT ]; then
		   echo "waiting for child processes to terminate"
		   SENT=sent
	       fi
	   done
	   rm -f $LOCKFILE_PATH
	   echo "stopped"
       fi
    else
	echo "$SERVICE_NAME is not running"
    fi
}

case $1 in
    restart)
	stop
	start
	;;
    start)
	start
	;;
    stop)
	stop
	;;
esac
