#!/bin/sh
#
# chkconfig: 2345 91 9
# description: Starts and stops the SPK compiler daemon
#

DATABASE=spktest
DBHOST=localhost
DBUSER=tester
DBPASSWD=tester
BIN=/usr/local/bin/spktest
MODE=test
SHOST=jobqserver
SPORT=9001
MAX_CONCURRENT=4

SERVICE_ROOT=spkcmp
SERVICE_NAME=${SERVICE_ROOT}testd
LOCKFILE_PATH=/tmp/lock_$SERVICE_NAME

ulimit -c 10000000  # this enables a core dump if the compiler crashes

start() {
    $BIN/${SERVICE_ROOT}d.pl $DATABASE $DBHOST $DBUSER $DBPASSWD $MODE $SHOST $SPORT $MAX_CONCURRENT
    echo "started"
}
stop() {
    if [ -f $LOCKFILE_PATH ]; then
       PID=`cat $LOCKFILE_PATH`
       kill $PID
       while sleep 1 && [ -f $LOCKFILE_PATH ]; do
	   if [ -z $SENT ]; then
	       echo "waiting for child processes to terminate"
	       SENT=sent
	   fi
       done
       rm -f $LOCKFILE_PATH
       echo "stopped"
    else
	echo "$SERVICE_NAME is not running"
    fi
}

case $1 in
    restart)
	stop
	start
	;;
    start)
	start
	;;
    stop)
	stop
	;;
esac
