/**********************************************************************
From:   Resource Facility for Population Kinetics                    
        Department of Bioengineering Box 352255                      
        University of Washington                                     
        Seattle, WA 98195-2255                                       

This file is part of the System for Population Kinetics (SPK), which
was developed with support from NIH grants RR-12609 and P41-
EB001975. Please cite these grants in any publication for which this
software is used and send a notification to the address given above.

SPK is Copyright (C) 1998-2003, by the University of Washington,
Resource Facility for Population Kinetics, and is made available as
free open source software under the terms of the University of
Washington Free-Fork License as a public service.  A copy of the
License can be found in the COPYING file in the root directory of this
distribution.
**********************************************************************/
package uw.rfpk.mda.saamii.preparation;

import javax.swing.table.*;
import uw.rfpk.mda.saamii.compartment.*;

/**
 *
 * @author  Jiaji Du
 */
public class InputFrame extends javax.swing.JFrame {
    
    /** Creates new form InputFrame */
    public InputFrame() {
        initComponents();
        String[] header = {"Column 1", "Column 2", "Column 3", "Column 4", "Column 5"};
        jTable1.setModel(new DefaultTableModel(header, 5));
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        popRadioButton = new javax.swing.JRadioButton();
        indRadioButton = new javax.swing.JRadioButton();
        estCheckBox = new javax.swing.JCheckBox();
        simCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        loadButton = new javax.swing.JButton();
        dataTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        compRadioButton = new javax.swing.JRadioButton();
        numRadioButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        foRadioButton = new javax.swing.JRadioButton();
        ehRadioButton = new javax.swing.JRadioButton();
        laRadioButton = new javax.swing.JRadioButton();
        mbRadioButton = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        feButton = new javax.swing.JButton();
        crButton = new javax.swing.JButton();
        ceButton = new javax.swing.JButton();
        emButton = new javax.swing.JButton();
        OKButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        niTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        sdComboBox = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        tlComboBox = new javax.swing.JComboBox();
        problemTextArea = new javax.swing.JTextArea();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("MDA - Input Preparation");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setText("Please enter a problem identifier with maximum of 100 characters");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 2, 12);
        getContentPane().add(jLabel1, gridBagConstraints);

        popRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        popRadioButton.setText("Population Analysis");
        buttonGroup1.add(popRadioButton);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(popRadioButton, gridBagConstraints);

        indRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        indRadioButton.setText("Individual Analysis");
        buttonGroup1.add(indRadioButton);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        getContentPane().add(indRadioButton, gridBagConstraints);

        estCheckBox.setFont(new java.awt.Font("Dialog", 0, 12));
        estCheckBox.setText("Parameter Estimation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(estCheckBox, gridBagConstraints);

        simCheckBox.setFont(new java.awt.Font("Dialog", 0, 12));
        simCheckBox.setText("Data Simulation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        getContentPane().add(simCheckBox, gridBagConstraints);

        jLabel3.setText("Select analysis type ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel2.setText("Enter data labels.  The label in Column 1 mast be ID.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 2, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(350, 100));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(300, 200));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 6, 12);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel4.setText("Load in a dataset");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 12, 4, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel5.setText("Select one or both");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 22, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel6.setText("Select one of them");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 22, 0, 12);
        getContentPane().add(jLabel6, gridBagConstraints);

        loadButton.setFont(new java.awt.Font("Dialog", 0, 12));
        loadButton.setText("Load");
        loadButton.setMargin(new java.awt.Insets(2, 8, 2, 8));
        loadButton.setPreferredSize(new java.awt.Dimension(50, 21));
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        jPanel1.add(loadButton);

        dataTextField.setPreferredSize(new java.awt.Dimension(269, 19));
        jPanel1.add(dataTextField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 12);
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel7.setText("Design a PK model");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 6, 0);
        getContentPane().add(jLabel7, gridBagConstraints);

        compRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        compRadioButton.setText("Compartmental Model");
        buttonGroup2.add(compRadioButton);
        compRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compRadioButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(compRadioButton, gridBagConstraints);

        numRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        numRadioButton.setText("Numerical Model");
        buttonGroup2.add(numRadioButton);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        getContentPane().add(numRadioButton, gridBagConstraints);

        jLabel8.setText("Specify fixed effect parameters and bounds");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 12, 4, 0);
        getContentPane().add(jLabel8, gridBagConstraints);

        jLabel9.setText("Specify covariance of random effect parameters");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 12, 4, 0);
        getContentPane().add(jLabel9, gridBagConstraints);

        jLabel10.setText("Specify residual unknown variability covariance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 12, 4, 0);
        getContentPane().add(jLabel10, gridBagConstraints);

        jLabel11.setText("Select an estimation method");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        getContentPane().add(jLabel11, gridBagConstraints);

        foRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        foRadioButton.setText("First Order");
        buttonGroup3.add(foRadioButton);
        jPanel3.add(foRadioButton);

        ehRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        ehRadioButton.setText("Expected Hessian");
        buttonGroup3.add(ehRadioButton);
        jPanel3.add(ehRadioButton);

        laRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        laRadioButton.setText("Laplace Appro.");
        buttonGroup3.add(laRadioButton);
        jPanel3.add(laRadioButton);

        mbRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        mbRadioButton.setText("Map Bayesian");
        buttonGroup3.add(mbRadioButton);
        jPanel3.add(mbRadioButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        getContentPane().add(jPanel3, gridBagConstraints);

        jLabel12.setText("Specify a residual unknown variability model");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 12, 4, 0);
        getContentPane().add(jLabel12, gridBagConstraints);

        feButton.setFont(new java.awt.Font("Dialog", 0, 12));
        feButton.setText("Enter");
        feButton.setPreferredSize(new java.awt.Dimension(64, 21));
        feButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        getContentPane().add(feButton, gridBagConstraints);

        crButton.setFont(new java.awt.Font("Dialog", 0, 12));
        crButton.setText("Enter");
        crButton.setPreferredSize(new java.awt.Dimension(64, 21));
        crButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        getContentPane().add(crButton, gridBagConstraints);

        ceButton.setFont(new java.awt.Font("Dialog", 0, 12));
        ceButton.setText("Enter");
        ceButton.setPreferredSize(new java.awt.Dimension(64, 21));
        ceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        getContentPane().add(ceButton, gridBagConstraints);

        emButton.setFont(new java.awt.Font("Dialog", 0, 12));
        emButton.setText("Enter");
        emButton.setPreferredSize(new java.awt.Dimension(64, 21));
        emButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        getContentPane().add(emButton, gridBagConstraints);

        OKButton.setText("OK");
        OKButton.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 1);
        getContentPane().add(OKButton, gridBagConstraints);

        cancelButton.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        getContentPane().add(cancelButton, gridBagConstraints);

        helpButton.setText("Help");
        helpButton.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 12, 12);
        getContentPane().add(helpButton, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel13.setForeground(java.awt.Color.red);
        jLabel13.setText("Empty");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        getContentPane().add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel14.setForeground(java.awt.Color.red);
        jLabel14.setText("Empty");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        getContentPane().add(jLabel14, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel15.setForeground(java.awt.Color.red);
        jLabel15.setText("Empty");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        getContentPane().add(jLabel15, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel16.setForeground(java.awt.Color.red);
        jLabel16.setText("Empty");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        getContentPane().add(jLabel16, gridBagConstraints);

        jLabel17.setText("Enter controling criteria for the computations");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        getContentPane().add(jLabel17, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel18.setText("No. of Iterations");
        jPanel2.add(jLabel18);

        niTextField.setPreferredSize(new java.awt.Dimension(50, 19));
        jPanel2.add(niTextField);

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel19.setText("Significant Digits");
        jPanel2.add(jLabel19);

        sdComboBox.setBackground(new java.awt.Color(255, 255, 255));
        sdComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        sdComboBox.setSelectedIndex(2);
        sdComboBox.setPreferredSize(new java.awt.Dimension(50, 19));
        jPanel2.add(sdComboBox);

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel20.setText("Tolerance");
        jPanel2.add(jLabel20);

        tlComboBox.setBackground(new java.awt.Color(255, 255, 255));
        tlComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        tlComboBox.setSelectedIndex(4);
        tlComboBox.setPreferredSize(new java.awt.Dimension(50, 19));
        jPanel2.add(tlComboBox);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        getContentPane().add(jPanel2, gridBagConstraints);

        problemTextArea.setLineWrap(true);
        problemTextArea.setRows(2);
        problemTextArea.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 6, 12);
        getContentPane().add(problemTextArea, gridBagConstraints);

        pack();
    }//GEN-END:initComponents

    private void compRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compRadioButtonActionPerformed
        String[] subjects = new String[10];
        for(int i = 0; i < 10; i++)
            subjects[i] = String.valueOf(i + 1);
        new DesignTool(subjects, "");
    }//GEN-LAST:event_compRadioButtonActionPerformed

    private void ceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceButtonActionPerformed
        new ErrorParamCov(this, true);
    }//GEN-LAST:event_ceButtonActionPerformed

    private void crButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crButtonActionPerformed
        new RandParamCov(this, true);
    }//GEN-LAST:event_crButtonActionPerformed

    private void feButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feButtonActionPerformed
        new FixedParam(this, true);
    }//GEN-LAST:event_feButtonActionPerformed

    private void emButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emButtonActionPerformed
        new ErrorModel(this, true);
    }//GEN-LAST:event_emButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        new Data(this, true);
    }//GEN-LAST:event_loadButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new InputFrame();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton ceButton;
    private javax.swing.JRadioButton compRadioButton;
    private javax.swing.JButton crButton;
    private javax.swing.JTextField dataTextField;
    private javax.swing.JRadioButton ehRadioButton;
    private javax.swing.JButton emButton;
    private javax.swing.JCheckBox estCheckBox;
    private javax.swing.JButton feButton;
    private javax.swing.JRadioButton foRadioButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JRadioButton indRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton laRadioButton;
    private javax.swing.JButton loadButton;
    private javax.swing.JRadioButton mbRadioButton;
    private javax.swing.JTextField niTextField;
    private javax.swing.JRadioButton numRadioButton;
    private javax.swing.JRadioButton popRadioButton;
    private javax.swing.JTextArea problemTextArea;
    private javax.swing.JComboBox sdComboBox;
    private javax.swing.JCheckBox simCheckBox;
    private javax.swing.JComboBox tlComboBox;
    // End of variables declaration//GEN-END:variables
    
}
