/**********************************************************************
From:   Resource Facility for Population Kinetics                    
        Department of Bioengineering Box 352255                      
        University of Washington
        Seattle, WA 98195-2255                                       

This file is part of the System for Population Kinetics (SPK), which
was developed with support from NIH grants RR-12609 and P41-
EB001975. Please cite these grants in any publication for which this
software is used and send a notification to the address given above.

SPK is Copyright (C) 1998-2003, by the University of Washington,
Resource Facility for Population Kinetics, and is made available as
free open source software under the terms of the University of
Washington Free-Fork License as a public service.  A copy of the
License can be found in the COPYING file in the root directory of this
distribution.
**********************************************************************/
package uw.rfpk.mda;

import uw.rfpk.mda.nonmem.Utility;
import java.util.ArrayList;
import java.util.Vector;
import java.awt.Color;
import java.awt.Font;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.ListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/** This class generates default plots.
 *
 * @author  Jiaji Du
 */
public class DefaultPlot extends javax.swing.JDialog {
    
    /** Creates new form DefaultPlot
     * @param parent a JFrame object
     */
    private DefaultPlot(java.awt.Frame parent) {
        super(parent, false);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDialog1 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        curveList = new javax.swing.JList(model);
        displayButton = new javax.swing.JButton();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setTitle("Missind Data");
        jDialog1.setModal(true);
        jDialog1.setResizable(false);
        jScrollPane2.setViewportView(jList1);

        jDialog1.getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel1.setText("jLabel1");
        jDialog1.getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDialog1.getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Plot List");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("Please select individuals");
        jTextField1.setFocusable(false);
        getContentPane().add(jTextField1, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(curveList);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        displayButton.setText("Display");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        getContentPane().add(displayButton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        int[] selectedIndex = curveList.getSelectedIndices();
        if(selectedIndex.length == 1 && selectedIndex[0] < 0)
            return;
        int inds = indPointsAll.length;
        int[] startIndex = new int[inds];
        startIndex[0] = 0;
        for(int i = 1; i < inds; i++)
            startIndex[i] = startIndex[i - 1] + indPointsAll[i - 1];
        int nSelection = selections.length;
        boolean[] missingItem = new boolean[nSelection];
        double[][] dataX = null;
        double[][] dataY = null;
        String title;
        int l;
        for(int j = 0; j < selectedIndex.length; j++)
        {
            int rows = indPointsAll[selectedIndex[j]];
            int startRow = startIndex[selectedIndex[j]];
            Vector<double[][]> all = new Vector<double[][]>();
            double[][] dataOut;
            int nCurve = 0;
            for(int i = 0; i < nSelection; i++)
            {
                dataOut = Utility.removeMissingValue(dataXAll[i], dataYAll[i], startRow, startRow + rows - 1, false, false);
                if(dataOut == null)
                {
                    if(!selections[i].equals("MDV"))
                        JOptionPane.showMessageDialog(null, "Data missing for a curve.");
                    missingItem[i] = true;
                }
                else
                {
                    nCurve++;
                    missingItem[i] = false;
                    all.add(dataOut);
                }
            }
            if(nCurve > 0)
            {
                dataX = new double[nCurve][];
                dataY = new double[nCurve][];
                int i = 0;
                for(double[][] item : all)
                {
                    dataX[i] = item[0];
                    dataY[i] = item[1];
                    i++;
                }
            }
            else
                return;
            name = new String[nCurve];
            symbol = new int[nCurve];
            color = new Color[nCurve];
            int k = 0;
            for(int i = 0; i < nSelection; i++)
            {
                if(missingItem[i]) continue;
                if(selections[i].equals("DV"))
                {
                    name[k] = "DV";
                    symbol[k] = 0;
                    color[k] = Color.black;
                }
                else if(selections[i].equals("MDV"))
                {
                    name[k] = "Missing DV";
                    symbol[k] = 0;
                    color[k] = Color.red;
                }
                else
                {
                    name[k] = selections[i];
                    symbol[k] = 10;
                    color[k] = Color.black;
                }
                k++;
            }
            title = titleAll + " for ind = " + indIDNames[selectedIndex[j]];
            l = j - j / 10 * 10;
            plot(dataX, dataY, title, l * 50, l * 40, false, null);
        }
    }//GEN-LAST:event_displayButtonActionPerformed
    
    /** This method generates a PRED or IPRED versus DV plot.
     * @param dataLabels an ArrayList object containing data labels.
     * @param dataValues a data value matrix.
     * @param indIDs individual IDs.
     * @param itemX either PRED or IPRED.
     * @param byID the flag to spicify if the plot should be divided by ID.
     */
    public static void plotDVvsPRED(ArrayList dataLabels, double[][] dataValues,
                                    String[] indIDs, String itemX, boolean byID)
    {
        titleY = "DV";
        titleX = itemX;
        int indexPRED = dataLabels.indexOf(titleX);
        int indexDV = dataLabels.indexOf(titleY);
        if(indexPRED == -1 || indexDV == -1)
        {
            JOptionPane.showMessageDialog(null, "Report data were not found.", "Input Error",
                                          JOptionPane.ERROR_MESSAGE);
            return;
        }
        int rows = dataValues.length;
        int columns = 1;
        selections = new String[]{"DV"};
        int indexMDV = dataLabels.indexOf("MDV");
        if(indexMDV != -1)
        {
            columns = 2;
            selections = new String[]{"DV", "MDV"};
        }
        dataXAll = new double[columns][rows];
        dataYAll = new double[columns][rows];
        for(int i = 0; i < rows; i++)
        {
            dataXAll[0][i] = dataValues[i][indexPRED];
            dataYAll[0][i] = dataValues[i][indexDV];
        }
        if(indexMDV != -1)
        {
            double nan = Double.parseDouble("NaN");
            for(int i = 0; i < rows; i++)
            {
                dataXAll[1][i] = dataValues[i][indexPRED];
                if(dataValues[i][indexMDV] == 1)
                    dataYAll[1][i] = dataValues[i][indexDV];
                else
                    dataYAll[1][i] = nan;
            }
        }
        indPointsAll = getIndPoints(indIDs);
        int[] curveIndPoints1 = new int[indPointsAll.length];
        int[] curveIndPoints2 = new int[indPointsAll.length];
        Vector<double[][]> curveDataAll1 = new Vector<double[][]>();
        Vector<double[][]> curveDataAll2 = new Vector<double[][]>();
        int startIndex = 0;
        int nInd = indPointsAll.length;
        double[][] dataOut1;
        double[][] dataOut2 = null;
        DefaultListModel missingDVPred = new DefaultListModel();
        for(int i = 0; i < nInd; i++)
        {
            dataOut1 = Utility.removeMissingValue(dataXAll[0], dataYAll[0], startIndex, startIndex + indPointsAll[i] - 1, false, false);
            if(columns == 2)
                dataOut2 = Utility.removeMissingValue(dataXAll[1], dataYAll[1], startIndex, startIndex + indPointsAll[i] - 1, false, false);
            startIndex += indPointsAll[i];
            if(dataOut1 != null)
            {
                curveDataAll1.add(dataOut1);
                curveIndPoints1[i] = dataOut1[0].length;
            }
            else
            {
                missingDVPred.addElement("Subject ID: " + (i + 1));
//                JOptionPane.showMessageDialog(null, "Data values missing for individual " + (i + 1) + ".");
                curveIndPoints1[i] = 0;
            }
            if(columns == 2)
            {
                if(dataOut2 != null)
                {
                    curveDataAll2.add(dataOut2);
                    curveIndPoints2[i] = dataOut2[0].length;
                }
                else
                {
//                    JOptionPane.showMessageDialog(null, "Data values missing for individual " + (i + 1) + " in MDV.");
                    curveIndPoints2[i] = 0;
                }
            }
        }
        if(curveDataAll1.size() == 0)
        {
            JOptionPane.showMessageDialog(null, "All data value are missing.");
            return;
        }
        if(missingDVPred.size() > 0)
        {
            DefaultPlot dialog = new DefaultPlot(new JFrame());
            dialog.jList1.setModel(missingDVPred);
            dialog.jLabel1.setText("Missing Data for DV vs. " + itemX);
            dialog.jDialog1.setSize(300, 300);
            dialog.jDialog1.setVisible(true);
        }
        if(columns == 2 && curveDataAll2.size() == 0)
            columns = 1;
        indPoints = new int[columns][];
        indPoints[0] = curveIndPoints1;
        int curveLength1 = 0;
        int curveLength2 = 0;
        for(int j = 0; j < nInd; j++)
            curveLength1 += curveIndPoints1[j];
        if(columns == 2)
        {
            indPoints[1] = curveIndPoints2;
            for(int j = 0; j < nInd; j++)
                curveLength2 += curveIndPoints2[j];
        }
        double[][] dataX = new double[columns][];   
        double[][] dataY = new double[columns][];
        dataX[0] = new double[curveLength1];
        dataY[0] = new double[curveLength1];
        if(columns == 2)
        {
            dataX[1] = new double[curveLength2];
            dataY[1] = new double[curveLength2];
        }
        int j = 0;
        int k;
        for(Object item : curveDataAll1)
        {
            double[][] temp = (double[][])item;
            for(k = 0; k < temp[0].length; k++)
            {
                dataX[0][j + k] = temp[0][k];
                dataY[0][j + k] = temp[1][k];
            }
            j = j + k;
        }
        if(columns == 2)
        {
            j = 0;
            for(Object item : curveDataAll2)
            {
                double[][] temp = (double[][])item;
                for(k = 0; k < temp[0].length; k++)
                {
                    dataX[1][j + k] = temp[0][k];
                    dataY[1][j + k] = temp[1][k];
                }
                j = j + k;
            }
        }
        if(columns == 1)
        {
            name = new String[]{titleY};
            symbol = new int[]{0};
            color = new Color[]{Color.black};
        }
        else
        {
            name = new String[]{titleY, "Missing DV"};
            symbol = new int[]{0, 0};
            color = new Color[]{Color.black, Color.red};
        }
        titleAll = titleY + " VS " + titleX;
        setPlotRange(dataX, dataY, true);
        uLine = true;
        xLine = false;
        yLine = false;
        if(!byID)
            plot(dataX, dataY, titleAll, 0, 0, true, indIDs);
        else
            plotIndividual(indIDs);
    }
    
    /** This method generates a DV and (PRED or IPRED) versus TIME plot.
     * @param dataLabels an ArrayList object containing data labels.
     * @param dataValues a data value matrix.
     * @param indIDs individual IDs.
     * @param itemY either PRED or IPRED.
     * @param byID the flag to spicify if the plot should be divided by ID.
     */    
    public static void plotPREDDVvsTIME(ArrayList dataLabels, double[][] dataValues,
                                        String[] indIDs, String itemY, boolean byID)
    {
        titleX = "TIME";
        titleY = itemY + " DV ";
        int indexPRED = dataLabels.indexOf(itemY);
        int indexDV = dataLabels.indexOf("DV");
        int indexTIME = dataLabels.indexOf(titleX);
        if(indexPRED == -1 || indexDV == -1 || indexTIME == -1)
        {
            JOptionPane.showMessageDialog(null, "Report data were not found.", "Input Error",
                                          JOptionPane.ERROR_MESSAGE);
            return;
        }
        int rows = dataValues.length;
        int columns = 2;
        selections = new String[]{itemY, "DV"};
        int indexMDV = dataLabels.indexOf("MDV");
        if(indexMDV != -1)
        {
            columns = 3;
            selections = new String[]{itemY, "DV", "MDV"};
        }
        dataXAll = new double[columns][rows];
        dataYAll = new double[columns][rows];
        for(int i = 0; i < rows; i++)
        {
            dataYAll[0][i] = dataValues[i][indexPRED];
            dataYAll[1][i] = dataValues[i][indexDV];
            dataXAll[0][i] = dataValues[i][indexTIME];
            dataXAll[1][i] = dataValues[i][indexTIME];
        }
        if(indexMDV != -1)
        {
            double nan = Double.parseDouble("NaN");
            for(int i = 0; i < rows; i++)
            {
                dataXAll[2][i] = dataValues[i][indexTIME];
                if(dataValues[i][indexMDV] == 1)
                    dataYAll[2][i] = dataValues[i][indexDV];
                else
                    dataYAll[2][i] = nan;
            }
        }
        indPointsAll = getIndPoints(indIDs);
        int[] curveIndPoints1 = new int[indPointsAll.length];
        int[] curveIndPoints2 = new int[indPointsAll.length];
        int[] curveIndPoints3 = new int[indPointsAll.length];
        Vector<double[][]> curveDataAll1 = new Vector<double[][]>();
        Vector<double[][]> curveDataAll2 = new Vector<double[][]>();
        Vector<double[][]> curveDataAll3 = new Vector<double[][]>();
        int startIndex = 0;
        int nInd = indPointsAll.length;
        double[][] dataOut1, dataOut2;
        double[][] dataOut3 = null;
        DefaultListModel missingPredTime = new DefaultListModel();
        DefaultListModel missingDVTime = new DefaultListModel();
        for(int i = 0; i < nInd; i++)
        {
            dataOut1 = Utility.removeMissingValue(dataXAll[0], dataYAll[0], startIndex, startIndex + indPointsAll[i] - 1, false, false);
            dataOut2 = Utility.removeMissingValue(dataXAll[1], dataYAll[1], startIndex, startIndex + indPointsAll[i] - 1, false, false);
            if(columns == 3)
                dataOut3 = Utility.removeMissingValue(dataXAll[2], dataYAll[2], startIndex, startIndex + indPointsAll[i] - 1, false, false);
            startIndex += indPointsAll[i];
            if(dataOut1 != null)
            {
                curveDataAll1.add(dataOut1);
                curveIndPoints1[i] = dataOut1[0].length;
            }
            else
            {
                missingPredTime.addElement("Subject ID: " + (i + 1));
//                JOptionPane.showMessageDialog(null, "Data values missing for individual " + (i + 1) + " in PRED vs. TIME.");
                curveIndPoints1[i] = 0;
            }
            if(dataOut2 != null)
            {
                curveDataAll2.add(dataOut2);
                curveIndPoints2[i] = dataOut2[0].length;
            }
            else
            {
                missingDVTime.addElement("Subject ID: " + (i + 1));
//                JOptionPane.showMessageDialog(null, "Data values missing for individual " + (i + 1) + " in DV vs. TIME.");
                curveIndPoints2[i] = 0;
            }
            if(columns == 3)
            {
                if(dataOut3 != null)
                {
                    curveDataAll3.add(dataOut3);
                    curveIndPoints3[i] = dataOut3[0].length;
                }
                else
                {
//                    JOptionPane.showMessageDialog(null, "Data values missing for individual " + (i + 1) + " in MDV.");
                    curveIndPoints3[i] = 0;
                }
            }
        }
        if(curveDataAll1.size() == 0 || curveDataAll2.size() == 0)
        {
            JOptionPane.showMessageDialog(null, "All data value are missing.");
            return;
        }
        if(missingPredTime.size() > 0)
        {
            DefaultPlot dialog = new DefaultPlot(new JFrame());
            dialog.jList1.setModel(missingPredTime);
            dialog.jLabel1.setText("Missing Data for " + itemY + " vs. Time");
            dialog.jDialog1.setSize(300, 300);
            dialog.jDialog1.setVisible(true);
        }
        if(missingDVTime.size() > 0)
        {
            DefaultPlot dialog = new DefaultPlot(new JFrame());
            dialog.jList1.setModel(missingDVTime);
            dialog.jLabel1.setText("Missing Data for DV vs. Time");
            dialog.jDialog1.setSize(300, 300);
            dialog.jDialog1.setVisible(true);
        }
        if(columns == 3 && curveDataAll3.size() == 0)
            columns = 2;
        indPoints = new int[columns][];
        indPoints[0] = curveIndPoints1;
        indPoints[1] = curveIndPoints2;
        int curveLength1 = 0;
        int curveLength2 = 0;
        int curveLength3 = 0;
        for(int j = 0; j < nInd; j++)
        {
            curveLength1 += curveIndPoints1[j];
            curveLength2 += curveIndPoints2[j];
        }
        if(columns == 3)
        {
            indPoints[2] = curveIndPoints3;
            for(int j = 0; j < nInd; j++)
                curveLength3 += curveIndPoints3[j];
        }
        double[][] dataX = new double[columns][];   
        double[][] dataY = new double[columns][];
        dataX[0] = new double[curveLength1];
        dataY[0] = new double[curveLength1];
        dataX[1] = new double[curveLength2];
        dataY[1] = new double[curveLength2];
        if(columns == 3)
        {
            dataX[2] = new double[curveLength3];
            dataY[2] = new double[curveLength3];
        }
        int j = 0;
        int k;
        for(Object item : curveDataAll1)
        {
            double[][] temp = (double[][])item;
            for(k = 0; k < temp[0].length; k++)
            {
                dataX[0][j + k] = temp[0][k];
                dataY[0][j + k] = temp[1][k];
            }
            j = j + k;
        }
        j = 0;
        for(Object item : curveDataAll2)
        {
            double[][] temp = (double[][])item;
            for(k = 0; k < temp[0].length; k++)
            {
                dataX[1][j + k] = temp[0][k];
                dataY[1][j + k] = temp[1][k];
            }
            j = j + k;
        }
        if(columns == 3)
        {
            j = 0;
            for(Object item : curveDataAll3)
            {
                double[][] temp = (double[][])item;
                for(k = 0; k < temp[0].length; k++)
                {
                    dataX[2][j + k] = temp[0][k];
                    dataY[2][j + k] = temp[1][k];
                }
                j = j + k;
            }
        }
        if(columns ==2)
        {
            name = new String[]{itemY, "DV"};
            symbol = new int[]{10, 0};
            color = new Color[]{Color.black, Color.black};
            titleAll = titleY + " Versus " + titleX;
        }
        else
        {
            name = new String[]{itemY, "DV", "Missing DV"};
            symbol = new int[]{10, 0, 0};
            color = new Color[]{Color.black, Color.black, Color.red};
            titleAll = titleY + " Versus " + titleX;
        }
        setPlotRange(dataX, dataY, false);
        xLine = false;
        yLine = false;
        uLine = false;
        if(!byID)
            plot(dataX, dataY, titleAll, 0, 0, true, indIDs);
        else
            plotIndividual(indIDs);
    }
    
    private static void setPlotRange(double[][] dataXAll, double[][] dataYAll, boolean isEqual)
    {
        if(isEqual)
        {
            double[] boundsX = findBounds(dataXAll);
            double[] boundsY = findBounds(dataYAll);
            double min = Math.min(boundsX[0], boundsY[0]);
            double max = Math.max(boundsX[1], boundsY[1]);
            double[] range = Plotter.optDivisions(6, min, max);
            minX = minY = range[0];
            maxX = maxY = range[1];
            nHDivi = nVDivi = (int)(range[2] + 0.1);
        }
        else
        {
            
            double[] rangeX = Plotter.getDefaultRange(dataXAll, false);
            double[] rangeY = Plotter.getDefaultRange(dataYAll, false);
            minX = rangeX[0];
            maxX = rangeX[1];
            minY = rangeY[0];
            maxY = rangeY[1];
            nHDivi = (int)(rangeX[2] + 0.1);
            nVDivi = (int)(rangeY[2] + 0.1);
        }
    }
    
    private static double[] findBounds(double[][] data)
    {
        double min = data[0][0];
        double max = min;
        for(int i = 0; i < data.length; i++)
            for(int j = 0; j < data[i].length; j++)
            {
                max = Math.max(max, data[i][j]);
                min = Math.min(min, data[i][j]);
            }
        double[] bounds = {min, max};
        return bounds;
    }
    
    private static void plotIndividual(String[] indIDs)
    {
        indPointsAll = getIndPoints(indIDs);
        indIDNames = new String[indPointsAll.length];
        indIDNames[0] = indIDs[0];
        model.clear();
        model.addElement("ind = " + indIDs[0]);
        int j = 0;
        for(int i = 1; i < indIDs.length; i++)
            if(!indIDs[i].equals(indIDNames[j]))
            {
                indIDNames[++j] = indIDs[i];
                model.addElement("ind = " + indIDs[i]);
            }
        DefaultPlot dialog = new DefaultPlot(new JFrame());
        dialog.setSize(160, 240);
        Dimension size = dialog.getToolkit().getScreenSize();
        dialog.setLocation(size.width / 2, size.height / 2);
        dialog.setVisible(true);
    }
    
    /** Get list of individual IDs.
     * @param indIDs list of IDs in the dataset.
     * @return list of individual IDs.
     */
    protected static int[] getIndPoints(String[] indIDs)
    {
        int count = 0;
        String id = indIDs[0];
        Vector<Integer> points = new Vector<Integer>();
        for(int i = 1; i < indIDs.length; i++)
        {
            count++;
            if(!id.equals(indIDs[i]))
            {
                points.add(new Integer(count));
                count = 0;
            }
            id = indIDs[i];
        }
        points.add(new Integer(++count));
        indPointsAll = new int[points.size()];
        for(int i = 0; i < points.size(); i++)
            indPointsAll[i] = ((Integer)points.get(i)).intValue();
        return indPointsAll;
    }
        
    private static void plot(double[][] dataX, double[][] dataY, String title, int x, int y,
                             boolean isIndividualized, String[] indIDs)
    {
        if(!isIndividualized) 
            indPoints = null;
        JFrame frame = new JFrame();
        Plotter plotter = new Plotter(dataX, dataY, title, titleX, titleY, name, symbol, color,
                                      xLine, yLine, uLine, false, false, true, true, 0, 0,
                                      null, null, addedLineColor, "Inside",
                                      nHDivi, nVDivi, 6, 6, 4, 4, 4, 4, maxX, minX, maxY, minY,
                                      titleFont, labelFont, legendFont, numberFont, 0, 0, 0, 0,
                                      true, true, false, false, false, 0, false, null, 2, 2, 
                                      frame, indPoints);
        plotter.setToolTipText("");
        frame.getContentPane().add(plotter);
        frame.setLocation(x, y);
	frame.setSize(500, 400);
	frame.setTitle("Model Design Agent Data Plot");	
	frame.setVisible(true);        
    }
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList curveList;
    private javax.swing.JButton displayButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
    private static double[][] dataXAll, dataYAll;
    private static double maxX, minX, maxY, minY;
    private static String[] name, indIDNames;
    private static int[] symbol, indPointsAll;
    private static int[][] indPoints;
    private static int nHDivi, nVDivi;
    private static Color[] color;
    private static String titleAll, titleX, titleY;
    private static final Font titleFont = new Font("SansSerif", Font.BOLD, 14);
    private static final Font labelFont = new Font("SansSerif", Font.BOLD, 12);
    private static final Font legendFont = new Font("SansSerif", Font.BOLD, 11);
    private static final Font numberFont = new Font("SansSerif", Font.BOLD, 10);
    private static Color[] addedLineColor = new Color[]{Color.black, Color.black, Color.black};
    private static boolean uLine, xLine, yLine;
    private static DefaultListModel model = new DefaultListModel();
    private static String[] selections;
}
