#!/bin/bash

if [ $UID -ne 0 ];
then
    echo "You must be root to run this program"
    exit 1
fi

source ../../../doc/webdir.sh

for f in *.pl; 
do
  doc=${f%.pl}
  pod2html $doc.pl > ${doc}.html
  scp ${doc}.html $WEBHOST:$WEBDIR/ops/utils/${doc}.html
done

for prog in *.p[lm]
do 
  chmod +x $prog
  cp $prog /usr/local/bin
done

exit 0