#!/bin/bash

USAGE="usage: $0 path"

if [ $UID -ne 0 ];
then
    echo "You must be root to run this program"
    exit 1
fi

if [ $# -ne 1 ];
then
    echo "Wrong number of arguments"
    echo $USAGE
    exit 2
fi

chmod +x $1
cp $1 /usr/local/bin
