#!/bin/csh
#
set SUCCESS=0
set ERROR_BAD_USAGE=1
set ERROR_INFILE=2
set ERROR_FREPORT=3
set ERROR_NO_EXECUTABLE=4
#
set dir=/usr/local/nmv
set f=g77
set o=' -O '
#
# This C shell script runs NM-TRAN and NONMEM V
# written by AJB 3/98 version 1.0
# The following lines are inserted by SETUP
#set dir=/home/nmv
#set f=f77
#set o=-O
set ndir=$dir/nm
set n="$ndir/NONMEM.o $ndir/BLKDAT.o $ndir/nonmem.a"
# for user library
set u=
rm -f FSUBS* FLIB FREPORT LINK.LNK nonmem >& /dev/null
if ($#argv != 2) then
echo Usage: nmfe5 infile outfile
exit $ERROR_BAD_USAGE
endif
if !(-e $1) then
echo File $1 does not exist.
exit $ERROR_INFILE
endif
set s=
$dir/tr/nmtran.exe < $1
if !(-e FREPORT) exit $ERROR_FREPORT
$dir/util/nmlink5.exe
if (-e FSUBS) then
cp FSUBS FSUBS.f
set s=FSUBS.f
endif
$f -o nonmem $o $s `cat LINK.LNK` $n $u
if !(-e nonmem) then
echo No nonmem execution.
exit $ERROR_NO_EXECUTABLE
endif
echo Starting nonmem execution ...
./nonmem < FCON > $2
#
exit $SUCCESS 
