#!/bin/sh
#
# chkconfig: 2345 91 9
# description: Starts and stops the SPK runtime daemon
#

DATABASE=spktest
DBHOST=localhost
DBUSER=tester
DBPASSWD=tester
MODE=test

SERVICE_ROOT=spkrun
SERVICE_NAME=${SERVICE_ROOT}testd
LOCKFILE_PATH=/tmp/lock_$SERVICE_NAME

ulimit -c 10000000  # this enables a core dump if the compiler crashes

start() {
    /usr/local/bin/${SERVICE_ROOT}d.pl $DATABASE $DBHOST $DBUSER $DBPASSWD $MODE
    echo "started"
}
stop() {
    if [ -f $LOCKFILE_PATH ]; then
       PID=`cat $LOCKFILE_PATH`
       kill $PID
       while sleep 1 && [ -f $LOCKFILE_PATH ]; do
	   if [ -z $SENT ]; then
	       echo "waiting for child processes to terminate"
	       SENT=sent
	   fi
       done
       echo "stopped"
    else
	echo "$SERVICE_NAME is not running"
    fi
}

case $1 in
    restart)
	stop
	start
	;;
    start)
	start
	;;
    stop)
	stop
	;;
esac
