#!/bin/sh
#
# chkconfig: 2345 91 9
# description: Starts and stops the SPK test trace server

BIN=/usr/local/bin/spktest
MODE=test
SERVICE_ROOT=trace
SERVICE_NAME=${SERVICE_ROOT}testd
LOCKFILE_PATH=/tmp/lock_$SERVICE_NAME

ulimit -c 10000000  # this enables a core dump if the compiler crashes

start() {
    $BIN/${SERVICE_ROOT}d.pl $MODE
    echo "started"
}
stop() {
    if [ -f $LOCKFILE_PATH ]; then
       PID=`cat $LOCKFILE_PATH`
       kill $PID
       if [ $? -ne 0 ]; then
	   rm -f $LOCKFILE_PATH
	   echo "stopped"
       else
	   while sleep 1 && [ -f $LOCKFILE_PATH ]; do
	       if [ -z $SENT ]; then
		   echo "waiting for child processes to terminate"
		   SENT=sent
	       fi
	   done
	   rm -f $LOCKFILE_PATH
	   echo "stopped"
       fi
    else
	echo "$SERVICE_NAME is not running"
    fi
}

case $1 in
    restart)
	stop
	start
	;;
    start)
	start
	;;
    stop)
	stop
	;;
esac
