#!/bin/sh


if [ $UID -ne 0 ];
then
    echo "You must be root on aspkserver to perform this installation."
    echo "Be sure to use su - (not just su) when becoming root."
    exit 1
fi
echo "You can only run this from aspkserver."
echo "If the aspkserver login fails, that's the reason."

source ../../../doc/webdir.sh

SERVICE_ROOT=spkcmp
SERVICE_HOST=aspkserver

cp ${SERVICE_ROOT}d /etc/rc.d/init.d
cp ${SERVICE_ROOT}testd /etc/rc.d/init.d
ssh ${SERVICE_HOST} mkdir -p /usr/local/bin/spktest
cp ${SERVICE_ROOT}d.pl /usr/local/bin/spktest

echo "installed ${SERVICE_HOST}:/etc/rc.d/init.d/${SERVICE_ROOT}d"
echo "installed ${SERVICE_HOST}:/etc/rc.d/init.d/${SERVICE_ROOT}testd"
echo "installed ${SERVICE_HOST}:/usr/local/bin/spktest/${SERVICE_ROOT}d.pl"

D=${SERVICE_ROOT}d

scp $D.pl.html $WEBHOST:/$WEBDIR/man/$D.pl.html

