/**********************************************************************
From:   Resource Facility for Population Kinetics                    
        Department of Bioengineering Box 352255                      
        University of Washington                                     
        Seattle, WA 98195-2255                                       

This file is part of the System for Population Kinetics (SPK), which
was developed with support from NIH grants RR-12609 and P41-
EB001975. Please cite these grants in any publication for which this
software is used and send a notification to the address given above.

SPK is Copyright (C) 1998-2003, by the University of Washington,
Resource Facility for Population Kinetics, and is made available as
free open source software under the terms of the University of
Washington Free-Fork License as a public service.  A copy of the
License can be found in the COPYING file in the root directory of this
distribution.
**********************************************************************/
package uw.rfpk.mda.nonmem.wizard;

import uw.rfpk.mda.nonmem.Utility;
import org.netbeans.ui.wizard.*;
import javax.swing.JComponent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane; 
import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.Vector;

/**
 * This class defines a step to create the $MODEL record.
 * @author  Jiaji Du
 */
public class Model extends javax.swing.JPanel implements WizardStep {
    
    private StepDescriptor sd = new MyStepDescriptor(); 
    private JComponent panel = this; 
    private MDAIterator iterator = null;
    private DefaultListModel model = null; 
    private String attributes = "";
    private JWizardPane wizardPane = null;
    private boolean isValid = false;
    private int index = -1;
    private int compN = 0;

    /** Creates new form Model.
     * @param iter a MDAIterator object to initialize the field iterator.
     */
    public Model(MDAIterator iter) { 
        initComponents();
        iterator = iter; 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDialog1 = new javax.swing.JDialog();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jTextPane3 = new javax.swing.JTextPane();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        addButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        jTextPane1 = new javax.swing.JTextPane();
        jTextPane2 = new javax.swing.JTextPane();
        changeButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        jDialog1.getContentPane().setLayout(new java.awt.GridBagLayout());

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setTitle("Attributes");
        jDialog1.setBackground(java.awt.Color.white);
        jDialog1.setModal(true);
        jDialog1.setResizable(false);
        jCheckBox1.setText("INITIALOFF");
        jCheckBox1.setToolTipText("Compartment is initially off");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 24, 1, 12);
        jDialog1.getContentPane().add(jCheckBox1, gridBagConstraints);

        jCheckBox2.setText("NOOFF");
        jCheckBox2.setToolTipText("Compartment may not be turned on or off.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 24, 1, 12);
        jDialog1.getContentPane().add(jCheckBox2, gridBagConstraints);

        jCheckBox3.setText("NODOSE");
        jCheckBox3.setToolTipText("Compartment may not receive a dose.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 24, 1, 12);
        jDialog1.getContentPane().add(jCheckBox3, gridBagConstraints);

        jCheckBox4.setText("EQUILIBRIUM");
        jCheckBox4.setToolTipText("Compartment is an equilibrium compartment (implies NODOSE).");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 24, 1, 12);
        jDialog1.getContentPane().add(jCheckBox4, gridBagConstraints);

        jCheckBox5.setText("EXCLUDE");
        jCheckBox5.setToolTipText("Compartment amount is excluded from the amount of the output compartment.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 24, 1, 12);
        jDialog1.getContentPane().add(jCheckBox5, gridBagConstraints);

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(4, 54, 4, 54);
        jDialog1.getContentPane().add(jButton2, gridBagConstraints);

        jTextPane3.setBackground(new java.awt.Color(238, 238, 238));
        jTextPane3.setText("Multiple attributes may be selected.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 6, 12);
        jDialog1.getContentPane().add(jTextPane3, gridBagConstraints);

        jCheckBox6.setText("DEFOBSERVATION");
        jCheckBox6.setToolTipText("Compartment is the default observation compartment.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 24, 1, 12);
        jDialog1.getContentPane().add(jCheckBox6, gridBagConstraints);

        jCheckBox7.setText("DEFDOSE");
        jCheckBox7.setToolTipText("Compartment is the default dose compartment.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 24, 1, 12);
        jDialog1.getContentPane().add(jCheckBox7, gridBagConstraints);

        setLayout(new java.awt.GridBagLayout());

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 16, 0, 16);
        add(addButton, gridBagConstraints);

        upButton.setText("Up");
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 16, 7, 16);
        add(upButton, gridBagConstraints);

        downButton.setText("Down");
        downButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 52, 16);
        add(downButton, gridBagConstraints);

        jTextPane1.setBackground(new java.awt.Color(238, 238, 238));
        jTextPane1.setEditable(false);
        jTextPane1.setText("Enter the definition of each compartment: its name and attributes.\n(Note:  Attributes DEFDOSE and DEFOBSERVATION are required.\n            Compartment name and other attributes are optional.)");
        jTextPane1.setFocusable(false);
        jTextPane1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTextPane1.setMinimumSize(new java.awt.Dimension(500, 60));
        jTextPane1.setPreferredSize(new java.awt.Dimension(400, 70));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 10, 8);
        add(jTextPane1, gridBagConstraints);

        jTextPane2.setBackground(new java.awt.Color(238, 238, 238));
        jTextPane2.setEditable(false);
        jTextPane2.setText("List of the\ncompart-\nments\nyou have\nentered in\nNONMEM\nsyntax");
        jTextPane2.setFocusable(false);
        jTextPane2.setMaximumSize(new java.awt.Dimension(70, 81));
        jTextPane2.setMinimumSize(new java.awt.Dimension(70, 81));
        jTextPane2.setPreferredSize(new java.awt.Dimension(70, 81));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 8, 5);
        add(jTextPane2, gridBagConstraints);

        changeButton.setText("Change");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 16, 6, 16);
        add(changeButton, gridBagConstraints);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 10, 16);
        add(deleteButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 16);
        add(jSeparator1, gridBagConstraints);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(jSeparator2, gridBagConstraints);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(180, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(180, 100));
        model = new DefaultListModel();
        jList1 = new javax.swing.JList(model);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setFixedCellHeight(15);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 8, 12);
        add(jScrollPane1, gridBagConstraints);

        jLabel1.setText("NCOMPARTMENTS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 12, 0, 0);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("NEQUILIBRIUM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 12, 9, 0);
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("NPARAMETERS");
        jLabel3.setToolTipText("Enter 0 unless using P(n) as parameter names");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 12, 13, 2);
        add(jLabel3, gridBagConstraints);

        jButton1.setText("Attributes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 10, 12);
        add(jButton1, gridBagConstraints);

        jTextField1.setEditable(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(4, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 12, 0, 12);
        add(jTextField1, gridBagConstraints);

        jTextField2.setPreferredSize(new java.awt.Dimension(4, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        add(jTextField2, gridBagConstraints);

        jTextField3.setToolTipText("Enter 0 unless using P(n) as parameter names");
        jTextField3.setPreferredSize(new java.awt.Dimension(8, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 12, 13, 12);
        add(jTextField3, gridBagConstraints);

        jTextField4.setMaximumSize(new java.awt.Dimension(80, 25));
        jTextField4.setMinimumSize(new java.awt.Dimension(80, 25));
        jTextField4.setPreferredSize(new java.awt.Dimension(80, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        add(jTextField4, gridBagConstraints);

        jLabel4.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 12);
        add(jLabel4, gridBagConstraints);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(jSeparator3, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    private void init()
    {
        index = jList1.getSelectedIndex();
        if(index < 0)
        {
            jTextField4.setText("");
            clearAttributes();
        }
        else
        {
            // Reload selected value
            String selectedValue = (String)jList1.getSelectedValue();
            int beginIndex = selectedValue.indexOf("(") + 1;
            int endIndex = selectedValue.indexOf(")");
            selectedValue = selectedValue.substring(beginIndex, endIndex);
            String name = "";
            int end = -1;
            if(selectedValue.startsWith("\""))
            {
                end = selectedValue.indexOf("\"", 1);
                name = selectedValue.substring(0, ++end);
            }
            else if(selectedValue.startsWith("'"))
            {
                end = selectedValue.indexOf("'", 1);
                name = selectedValue.substring(0, ++end);
            }
            else
            {
                end = selectedValue.indexOf(" ");
                if(end != -1)
                {
                    name = selectedValue.substring(0, end);
                    selectedValue = selectedValue.substring(end);
                }
                else
                {
                    name = selectedValue;
                    selectedValue = "";
                }
            }
            jTextField4.setText(name);
            jCheckBox1.setSelected(selectedValue.indexOf(" INITIALOFF") != -1);
            jCheckBox2.setSelected(selectedValue.indexOf(" NOOFF") != -1);
            jCheckBox3.setSelected(selectedValue.indexOf(" NODOSE") != -1);
            if(iterator.getAdvan() == 9)
            {   
                jCheckBox4.setEnabled(true);
                jCheckBox5.setEnabled(true);
                jCheckBox4.setSelected(selectedValue.indexOf(" EQUILIBRIUM") != -1);
                jCheckBox5.setSelected(selectedValue.indexOf(" EXCLUDE") != -1);
            }
            else
            {
                jCheckBox4.setEnabled(false);
                jCheckBox5.setEnabled(false);
            }
            jCheckBox6.setSelected(selectedValue.indexOf(" DEFOBSERVATION") != -1);
            jCheckBox7.setSelected(selectedValue.indexOf(" DEFDOSE") != -1);
        }
    }
        
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        init();
        changeButton.setEnabled(true);
        deleteButton.setEnabled(true);
        Utility.setUpDownButton(index, model, upButton, downButton);
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        attributes = "";
        if(jCheckBox1.isSelected())
            attributes = attributes + " INITIALOFF";
        if(jCheckBox2.isSelected())
            attributes = attributes + " NOOFF";
        if(jCheckBox3.isSelected())
            attributes = attributes + " NODOSE";
        if(iterator.getAdvan() == 9 && jCheckBox4.isSelected())
            attributes = attributes + " EQUILIBRIUM";
        if(iterator.getAdvan() == 9 && jCheckBox5.isSelected())
            attributes = attributes + " EXCLUDE";
        if(jCheckBox6.isSelected())
            attributes = attributes + " DEFOBSERVATION";
        if(jCheckBox7.isSelected())
            attributes = attributes + " DEFDOSE";
        jDialog1.setVisible(false);
        jDialog1.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jCheckBox4.setEnabled(iterator.getAdvan() == 9);
        jCheckBox5.setEnabled(iterator.getAdvan() == 9);
        if(iterator.getAdvan() != 9) 
        {
            jCheckBox4.setSelected(false);
            jCheckBox5.setSelected(false);            
        }
        for(int i = 0; i < model.getSize(); i++)
        {
            if(((String)model.get(i)).indexOf(" DEFDOSE") != -1)
            {
                jCheckBox7.setEnabled(false);
                jCheckBox7.setSelected(false);
                break;
            }
        }
        for(int i = 0; i < model.getSize(); i++)
        {
            if(((String)model.get(i)).indexOf(" DEFOBSERVATION") != -1)
            {
                jCheckBox6.setEnabled(false);
                jCheckBox6.setSelected(false);
                break;
            }
        }
        jDialog1.setSize(260,300);
        jDialog1.setLocationRelativeTo(this);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if(index == -1) return;

        // Remove element
        model.removeElement(jList1.getSelectedValue());
        jTextField1.setText(String.valueOf(model.size()));
        jList1.setSelectedIndex(--index);
        init();
        
        // Set add button
        addButton.setEnabled(true);
        
        // Set left options
        if(model.getSize() == 0)
        {
            isValid = false;
            wizardPane.setLeftOptions(wizardPane.getUpdatedLeftOptions().toArray()); 
        }
        
        // Set up and down buttons
        Utility.setUpDownButton(index, model, upButton, downButton);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        // Construct element
        String name = jTextField4.getText().trim();
        if(name.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "The compartment name is missing.",
                                          "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Check if changeable
        for(int i = 0; i < model.getSize(); i++)
            if(i != index && ((String)model.get(i)).split(" ")[0].equals(name))
            {
                JOptionPane.showMessageDialog(null, "The compartment name '" + name + "' is already used.",
                                              "Input Error", JOptionPane.ERROR_MESSAGE);                
                return;
            }
        String element = "COMP=(" + name + attributes + ")";
        model.setElementAt(element, index);     
        jList1.setSelectedIndex(index);
    }//GEN-LAST:event_changeButtonActionPerformed

    private void downButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButtonActionPerformed
        jList1.setSelectedIndex(++index);
        init();
        if(index == 0)
        {
            changeButton.setEnabled(true);
            deleteButton.setEnabled(true);
        }
                
        // Set up and down buttons
        Utility.setUpDownButton(index, model, upButton, downButton);
    }//GEN-LAST:event_downButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // Construct element
        String name = jTextField4.getText().trim();
        if(name.equals(""))
        {
            name = "COMP" + (++compN);
        }
        
        // Check if addable
        for(int i = 0; i < model.getSize(); i++)
        {
            if(name.equals(((String)model.get(i)).split(" ")[0].substring(6)))
            {
                JOptionPane.showMessageDialog(null, "The name '" + name + "' is already used.",
                                              "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        clearAttributes();
        jButton1.doClick();
        
        String element = "COMP=(" + name + attributes + ")";

        // Add element
        model.add(++index, element);
        jTextField1.setText(String.valueOf(model.size()));
        jList1.setSelectedIndex(index);

        // Set up and down buttons
        Utility.setUpDownButton(index, model, upButton, downButton);
        
        // Set left options
//        String n1 = jTextField1.getText().trim();
        String n2 = jTextField2.getText().trim();
        String n3 = jTextField3.getText().trim();        
//        if(!n1.equals("") && !Utility.isPosIntNumber(n1))
//        {
//            JOptionPane.showMessageDialog(null, 
//                                          "The number of compartments other than the output compartment is " +
//                                          "not a positive integer",
//                                          "Input Error",  
//                                          JOptionPane.ERROR_MESSAGE); 
//            jTextField1.setText("");
//        }
        if(iterator.getAdvan() == 9 && !n2.equals("") && !Utility.isPosIntNumber(n2) && !n2.equals("0"))
        {
            JOptionPane.showMessageDialog(null, 
                                          "The number of equilibrium equations is " +
                                          "not a positive integer or zero.",
                                          "Input Error",  
                                          JOptionPane.ERROR_MESSAGE); 
            jTextField2.setText("");
        }
        else if(!n3.equals("") && !Utility.isPosIntNumber(n3) && !n3.equals("0"))
        {
            JOptionPane.showMessageDialog(null, 
                                          "The number of basic PK parameters is " +
                                          "not a positive integer or zero.",
                                          "Input Error",  
                                          JOptionPane.ERROR_MESSAGE); 
            jTextField3.setText("");
        }
        else
        {
            isValid = true;
            wizardPane.setLeftOptions(wizardPane.getUpdatedLeftOptions().toArray());
        }        
    }//GEN-LAST:event_addButtonActionPerformed

    private void clearAttributes()
    {
        attributes = "";
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
    }
    
    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
        jList1.setSelectedIndex(--index);
        init();
        
        // Set up and down buttons
        Utility.setUpDownButton(index, model, upButton, downButton);
    }//GEN-LAST:event_upButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton changeButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton downButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables

    /**
     * This method is to return the StepDescriptor object.
     * @return a StepDescriptor object.
     */    
    public StepDescriptor getStepDescription(){
	return sd;
    }

    private class MyStepDescriptor extends StepDescriptor{ 

	public Component getComponent(){
	    return panel;
	}
       
  	public String getContentItem(){
  	    return "Model Specification";
  	}

	public String getStepTitle(){
	    return "Model Specification";
	}

	public void showingStep(JWizardPane wizard){
            if(iterator.getIsBack())
            {
                iterator.setIsBack(false);
                return;
            }
            wizardPane = wizard;           
            if(iterator.getIsReload())
            {
                String text = iterator.getReload().getProperty("MODEL");
                if(text != null)
                {
                    text = text.trim().concat(" ");
                    iterator.getReload().remove("MODEL");
                    int beginIndex, endIndex;
                    if(text.indexOf("NCOMPARTMENTS=") != -1 || text.indexOf("NEQUILIBRIUM=") != -1 ||
                       text.indexOf("NPARAMETERS=") != -1)
                    {
                        String numbers = text.substring(6, text.indexOf("\n")).concat(" ");
                        beginIndex = numbers.indexOf("NCOMPARTMENTS=");
                        if(beginIndex != -1)
                        {
                            endIndex = numbers.indexOf(" ", beginIndex);
                            if(endIndex == -1) endIndex = numbers.length(); 
                            jTextField1.setText(numbers.substring(beginIndex + 14, endIndex));
                        }
                        beginIndex = numbers.indexOf("NEQUILIBRIUM=");
                        if(beginIndex != -1)
                        {
                            endIndex = numbers.indexOf(" ", beginIndex);
                            if(endIndex == -1) endIndex = numbers.length();
                            jTextField2.setText(numbers.substring(beginIndex + 13, endIndex));
                        }
                        beginIndex = numbers.indexOf("NPARAMETERS=");
                        if(beginIndex != -1)
                        {
                            endIndex = numbers.indexOf(" ", beginIndex);
                            if(endIndex == -1) endIndex = numbers.length();
                            jTextField3.setText(numbers.substring(beginIndex + 12, endIndex));
                        }
                    }

                    model.removeAllElements();
                    beginIndex = text.indexOf("COMP=(");
                    while(beginIndex != -1)
                    {
                        endIndex = text.indexOf(")", beginIndex);
                        model.addElement(checkAttribute(text.substring(beginIndex, endIndex + 1)));
                        beginIndex = text.indexOf("COMP=(", endIndex);
                    }
                    index = model.size() - 1;
                    jList1.setSelectedIndex(index);
                    setLastDefaultCompNumber();                    
                }
                else
                    for(int i = 0; i < model.size(); i++)
                        model.set(i, checkAttribute((String)model.get(i)));
                if(model.size() > 0)
                    init();
                else
                {
                    jTextField4.setText("");
                    clearAttributes();
                }
                if(iterator.getAdvan() == 6 && iterator.initAdvan.contains("model"))
                {
                    initModel();
                    iterator.initAdvan.remove("model");
                }
                isValid = true;
                wizardPane.setLeftOptions(wizardPane.getUpdatedLeftOptions().toArray());
            }
            else
            {
                if(iterator.getAdvan() == 6 && iterator.initAdvan.contains("model"))
                {
                    initModel();
                    iterator.initAdvan.remove("model");
                }
                else
                {
                    for(int i = 0; i < model.size(); i++)
                        model.set(i, checkAttribute((String)model.get(i)));
                    if(model.size() > 0)
                        init();
                    else
                    {
                        jTextField4.setText("");
                        clearAttributes();
                    }
                }
                isValid = true;
                wizardPane.setLeftOptions(wizardPane.getUpdatedLeftOptions().toArray());
            }
            jTextField1.setText(String.valueOf(model.size()));
            jTextField2.setEditable(iterator.getAdvan() == 9);
	}
        
        private void setLastDefaultCompNumber()
        {
            compN = 0;
            String s;
            for(int i = model.getSize() - 1; i > 0; i--)
            {
                s = (String)model.get(i);
                if(s.startsWith("COMP=(COMP"))
                {
                    if(s.indexOf(" ") != -1) 
                        s = s.substring(10);
                    else 
                        s = s.substring(10, s.length() - 1);
                    if(Utility.isPosIntNumber(s))
                        compN = Math.max(compN, Integer.parseInt(s));
                }
            }
        }

        private String checkAttribute(String element)
        {
            int end = element.indexOf(" ");
            if(end == -1)
                end = element.indexOf(")");
            String cName = element.substring(6, end);
            String attrs = null;
            if(element.indexOf(" ") != -1)
            {
                attrs = element.substring(element.indexOf(" "), element.length() - 1);
                if(iterator.getAdvan() != 9 && attrs.indexOf(" EQUILIBRIUM") != -1)
                {
                    element = element.replaceAll(" EQUILIBRIUM", "");
                    JOptionPane.showMessageDialog(null, "The attribute 'EQUILIBRIUM' has been removed from compartment '" + cName + "'\n" +
                                                 "because it is only for ADVAN9.", 
                                                  "Input Error", JOptionPane.ERROR_MESSAGE);
                }
                if(iterator.getAdvan() != 9 && attrs.indexOf(" EXCLUDE") != -1)
                {
                    element =element.replaceAll(" EXCLUDE", "");
                    JOptionPane.showMessageDialog(null, "The attribute 'EXCLUDE' has been removed from compartment '" + cName + "'\n" +
                                                  "because it is only for ADVAN9.", 
                                                  "Input Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            return element;
        }
        
        public boolean checkingStep(JWizardPane wizard){
            if(model.getSize() == 0)
            {
                JOptionPane.showMessageDialog(null, "Compartment was missing.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            // Find default dose and default observation
            boolean hasIt = false;
            for(int i = 0; i < model.getSize(); i++)
            {
                if(((String)model.get(i)).indexOf(" DEFDOSE") != -1)
                {
                    hasIt = true;
                    break;
                }
            }
            if(!hasIt)
            {
                String s = (String)model.get(0);                
                model.set(0, s.substring(0, s.length() - 1) + " DEFDOSE)");
                init();
                JOptionPane.showMessageDialog(null, "The 'DEFDOSE' was not found in the compartments." + 
                                              "\nThe MDA added it to the first compartment as default.",
                                              "Warning Message", JOptionPane.WARNING_MESSAGE);
                return false;
            }
            hasIt = false;
            for(int i = 0; i < model.getSize(); i++)
            {
                if(((String)model.get(i)).indexOf(" DEFOBSERVATION") != -1)
                {
                    hasIt = true;
                    break;
                }
            }
            if(!hasIt)
            {
                String s = (String)model.get(0);                
                model.set(0, s.substring(0, s.length() - 1) + " DEFOBSERVATION)");
                init();
                JOptionPane.showMessageDialog(null, "The 'DEFOBSERVATION' was not found in the compartments." + 
                                              "\nThe MDA added it to the first compartment as default.",
                                              "Warning Message", JOptionPane.WARNING_MESSAGE);
                return false;
            }
            return true;
        }
        
	public void hidingStep(JWizardPane wizard){
            if(iterator.getIsBack()) return;
            int size = model.getSize();
            MDAObject object = (MDAObject)wizard.getCustomizedObject();
            String record = "";
            String n1 = jTextField1.getText().trim();
            if(!n1.equals(""))
            {
                record += " NCOMPARTMENTS=" + n1;
                iterator.setNComp(Integer.parseInt(n1));
            }
            String n2 = jTextField2.getText().trim();
            if(!n2.equals("") && iterator.getAdvan() == 9)
                record += " NEQUILIBRIUM=" + n2;
            String n3 = jTextField3.getText().trim();
            if(!n3.equals(""))
            {
                if(!n3.equals("0"))
                {
                    if(JOptionPane.showConfirmDialog(null, 
                        "You have set a non-zero NPARAMETERS, which means that\n" +
                        "the variables P(1), P(2), ..., P(NPARAMETERS) will be used\n" + 
                        "in the model expressions.  Do you really intend to do this?\n" +
                        "If you click the No button, NPARAMETERS will be reset to 0.",
                        "Question Dialog", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) != 0)
                    {
                         n3 = "0";
                         jTextField3.setText(n3);
                    }
                }
                record += " NPARAMETERS=" + n3 + " ";
            }
   
            // Set records
            for(int i = 0; i < size; i++)
                record += "\n" + ((String)model.get(i)).replaceAll("\r", "");
            object.getRecords().setProperty("Model", "$MODEL" + record);
            
            // Set source
            String[][] compartments = new String[size + 1][];
            compartments[0] = new String[3]; 
            if(!n1.equals(""))
                compartments[0][0] = n1;
            else
                compartments[0][0] = String.valueOf(size);
            if(!n2.equals("") && iterator.getAdvan() == 9)
                compartments[0][1] = n2;
            else
                compartments[0][1] = "0";
            if(!n3.equals(""))
                compartments[0][2] = n3;
            else
                compartments[0][2] = null;
            for(int i = 1; i <= size; i++)
            {
                String name = "";
                int end = -1;
                String compartment = ((String)model.get(i - 1)).substring(6);
                if(compartment.startsWith("\""))
                {
                    end = compartment.indexOf("\"", 1);
                    name = compartment.substring(1, end++);
                }
                else if(compartment.startsWith("'"))
                {
                    end = compartment.indexOf("'", 1);
                    name = compartment.substring(1, end++);
                }
                else
                {
                    end = compartment.indexOf(" ");
                    if(end == -1) end = compartment.indexOf(")");
                    name = compartment.substring(0, end);
                }
                compartment = compartment.substring(end);          
                compartments[i] = new String[8];                
                compartments[i][0] = name; 
                if(compartment.indexOf(" INITIALOFF") != -1)
                    compartments[i][1] = "yes";
                else
                    compartments[i][1] = "no";
                
                if(compartment.indexOf(" NOOFF") != -1)
                    compartments[i][2] = "yes";
                else
                    compartments[i][2] = "no";
                if(compartment.indexOf(" NODOSE") != -1)
                    compartments[i][3] = "yes";
                else
                    compartments[i][3] = "no";
                if(compartment.indexOf(" EQUILIBRIUM") != -1)
                    compartments[i][4] = "yes";
                else
                    compartments[i][4] = "no";
                if(compartment.indexOf(" EXCLUDE") != -1)
                    compartments[i][5] = "yes";
                else
                    compartments[i][5] = "no";
                if(compartment.indexOf(" DEFOBSERVATION") != -1)
                    compartments[i][6] = "yes";
                else
                    compartments[i][6] = "no";
                if(compartment.indexOf(" DEFDOSE") != -1)
                    compartments[i][7] = "yes";
                else
                    compartments[i][7] = "no";
            }
            object.getSource().model = compartments;
	}

	public boolean isValid(){
            return isValid;
	}

	public ActionListener getHelpAction(){
	    return new ActionListener(){
                public void actionPerformed(ActionEvent e){  
                }
            };
	}
        
        public String getHelpID() {
            return "Prepare_Input_Model_Parameters";
        }
        
        private void initModel()
        {
            int adn = iterator.adn;
            if(adn > 0)
            {
                model.removeAllElements();
                index = -1;
            }
            switch(adn)
            {
                case 1: 
                    model.add(++index, "COMP=(CENTRAL DEFDOSE DEFOBSERVATION NOOFF)");
                    break;
                case 2: 
                    model.add(++index, "COMP=(DEPOT INITIALOFF DEFDOSE)");
                    model.add(++index, "COMP=(CENTRAL DEFOBSERVATION NOOFF)");
                    break;
                case 3:
                    model.add(++index, "COMP=(CENTRAL DEFOBSERVATION DEFDOSE NOOFF)");
                    model.add(++index, "COMP=(PERIPH NOOFF)");
                    break;
                case 4:
                    model.add(++index, "COMP=(DEPOT INITIALOFF DEFDOSE)");
                    model.add(++index, "COMP=(CENTRAL DEFOBSERVATION NOOFF)");
                    model.add(++index, "COMP=(PERIPH NOOFF)");
                    break;
                case 10:
                    model.add(++index, "COMP=(CENTRAL DEFDOSE DEFOBSERVATION NOOFF)");
                    break;
                case 11:
                    model.add(++index, "COMP=(CENTRAL DEFOBSERVATION DEFDOSE NOOFF)");
                    model.add(++index, "COMP=(PERIPH1 NOOFF)");
                    model.add(++index, "COMP=(PERIPH2 NOOFF)");
                    break;
                case 12:
                    model.add(++index, "COMP=(DEPOT INITIALOFF DEFDOSE)");
                    model.add(++index, "COMP=(CENTRAL DEFOBSERVATION NOOFF)");
                    model.add(++index, "COMP=(PERIPH1 NOOFF)");
                    model.add(++index, "COMP=(PERIPH2 NOOFF)");
            }
            jTextField1.setText(String.valueOf(model.size()));
            jList1.setSelectedIndex(index);
        }
    }
}
